"use client";
/* eslint-disable @next/next/no-img-element -- Receipt previews use device-local Blob URLs. */

import Link from "next/link";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { parseReceiptText } from "./ocr";
import { prepareReceiptImage } from "./image";
import { useShoppingFile } from "../shopping-input";

type Currency="HKD"|"CNY"|"TWD"|"JPY"|"KRW"|"THB"|"USD";
type Category={id:string;name:string};
type Item={id:string;name:string;quantity:string;size:string;unit:"ml"|"L"|"g"|"kg"|"件";category:string};
type Data={updatedAt?:number;expenses?:unknown[];categories?:Category[];rates?:Partial<Record<Currency,number>>;[key:string]:unknown};
const SNAPSHOT="antony-app-data-v5",PURCHASES="antony-purchase-items-v1",DB="antony-expenses-db",STORE="app-data",KEY="current";
const defaults:Category[]=["交通費","早餐","午餐","晚餐","買餸","日常消費","睇戲","電話費","上網費","其他"].map((name,index)=>({id:"cat-"+(index+1),name}));
const currencies:Currency[]=["HKD","CNY","TWD","JPY","KRW","THB","USD"];
const id=()=>Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,9);
const today=()=>new Date().toLocaleDateString("en-CA");
function dataFromStorage():Data{try{const raw=localStorage.getItem(SNAPSHOT);if(raw)return JSON.parse(raw) as Data}catch{}return{updatedAt:0,expenses:[],categories:defaults,rates:{HKD:1}}}
function writeSnapshot(data:Data){localStorage.setItem(SNAPSHOT,JSON.stringify(data));localStorage.setItem("antony-expenses",JSON.stringify(data.expenses||[]));localStorage.setItem("antony-categories",JSON.stringify(data.categories||defaults));localStorage.setItem("antony-rates",JSON.stringify(data.rates||{HKD:1}))}
function readDatabase(){return new Promise<Data|null>((resolve,reject)=>{const open=indexedDB.open(DB,1);open.onerror=()=>reject(open.error);open.onsuccess=()=>{const database=open.result;if(!database.objectStoreNames.contains(STORE)){database.close();resolve(null);return}const tx=database.transaction(STORE,"readonly"),request=tx.objectStore(STORE).get(KEY);request.onsuccess=()=>resolve((request.result||null) as Data|null);request.onerror=()=>reject(request.error);tx.oncomplete=()=>database.close()}})}
function writeDatabase(data:Data){return new Promise<void>((resolve,reject)=>{const open=indexedDB.open(DB,1);open.onupgradeneeded=()=>{if(!open.result.objectStoreNames.contains(STORE))open.result.createObjectStore(STORE)};open.onerror=()=>reject(open.error);open.onsuccess=()=>{const database=open.result,tx=database.transaction(STORE,"readwrite");tx.objectStore(STORE).put(data,KEY);tx.oncomplete=()=>{database.close();resolve()};tx.onerror=()=>{database.close();reject(tx.error)}}})}
function suggestedCategory(name:string){const value=name.toLowerCase();return ["奶","milk","蛋","egg","米","菜","肉","魚","bread","水果","fruit","咖啡","coffee","茶","tea","水","water"].some(word=>value.includes(word))?"買餸":["洗頭","牙膏","紙巾","清潔","shampoo","tissue"].some(word=>value.includes(word))?"日常消費":""}

export default function ReceiptPage(){
 const[app,setApp]=useState<Data|null>(null),[preview,setPreview]=useState(""),[sourceFile,setSourceFile]=useState<File|null>(null),[fileName,setFileName]=useState(""),[merchant,setMerchant]=useState(""),[date,setDate]=useState(today()),[currency,setCurrency]=useState<Currency>("HKD"),[amount,setAmount]=useState(""),[category,setCategory]=useState("買餸"),[items,setItems]=useState<Item[]>([]),[message,setMessage]=useState("未加入購物憑證"),[saving,setSaving]=useState(false),[scanning,setScanning]=useState(false),[scanProgress,setScanProgress]=useState(0),[ocrText,setOcrText]=useState("");
 const incomingFile=useShoppingFile(), consumed=useRef<File|null>(null), scanLock=useRef(false);
 const categories=app?.categories?.length?app.categories:defaults,number=Number(amount)||0,rate=currency==="HKD"?1:Number(app?.rates?.[currency])||1;
 useEffect(()=>{let active=true;const timer=window.setTimeout(()=>{void readDatabase().catch(()=>null).then(database=>{const local=dataFromStorage(),loaded=database&&(Number(database.updatedAt)||0)>=(Number(local.updatedAt)||0)?database:local;if(active){setApp(loaded);setCategory(loaded.categories?.find(item=>item.name==="買餸")?.name||loaded.categories?.[0]?.name||"其他")}})},0);return()=>{active=false;window.clearTimeout(timer)}},[]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
 function loadFile(file:File){setPreview(URL.createObjectURL(file));setSourceFile(file);setFileName(file.name||"相片");setOcrText("");setMerchant("");setAmount("");setItems([]);void scanReceipt(file)}
 function chooseFile(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(file&&!scanLock.current)loadFile(file);event.target.value=""}
 useEffect(()=>{if(!incomingFile||consumed.current===incomingFile)return;const timer=window.setTimeout(()=>{if(consumed.current===incomingFile)return;consumed.current=incomingFile;loadFile(incomingFile)},0);return()=>window.clearTimeout(timer)},[incomingFile]); // eslint-disable-line react-hooks/exhaustive-deps
 async function scanReceipt(file:File){if(scanLock.current)return;scanLock.current=true;setScanning(true);setScanProgress(0);setMessage("正在自動辨認；首次使用需要下載語言資料…");let worker:Awaited<ReturnType<typeof import("tesseract.js")["createWorker"]>>|null=null;try{const{createWorker}=await import("tesseract.js");worker=await createWorker(["eng","chi_tra","chi_sim"],undefined,{logger:update=>{if(typeof update.progress==="number")setScanProgress(Math.round(update.progress*100))}});const result=await worker.recognize(await prepareReceiptImage(file));setOcrText(result.data.text.trim());const parsed=parseReceiptText(result.data.text);if(parsed.merchant)setMerchant(parsed.merchant);setItems(parsed.items.map(item=>({id:id(),...item,category:suggestedCategory(item.name)||category})));if(parsed.amount){setAmount(parsed.amount);setMessage(`已辨認總額 ${currency} ${parsed.amount}${parsed.items.length?`，並保留 ${parsed.items.length} 項商品資料`:""}；請核對後入帳`)}else{setMessage("未找到明確應付總額；請直接輸入總額後入帳")}}catch{setMessage("未能辨認，請直接輸入總額後入帳；相片沒有上載")}finally{if(worker)await worker.terminate().catch(()=>undefined);scanLock.current=false;setScanning(false)}}
 async function save(){if(!app||number<=0){setMessage("請先輸入整張單總額");return}const selected=categories.find(item=>item.name===category)||categories[0];if(!selected){setMessage("找不到支出分類");return}setSaving(true);const now=Date.now(),expenseId=id(),note=[merchant?"購物："+merchant:"購物憑證",fileName?"來源："+fileName:""].filter(Boolean).join(" · "),expense={id:expenseId,amount:number,currency,hkdAmount:number*rate,rate,categoryId:selected.id,date,note,createdAt:now,expenseType:"daily"},next={...app,updatedAt:Math.max(now,(Number(app.updatedAt)||0)+1),expenses:[expense,...(app.expenses||[])],categories,rates:{HKD:1,...app.rates}};try{writeSnapshot(next);await writeDatabase(next).catch(()=>undefined);const stock=items.filter(item=>item.name.trim()).map(item=>({id:id(),name:item.name.trim(),quantity:Math.max(1,Number(item.quantity)||1),size:Number(item.size)||null,unit:item.unit,category:item.category,purchasedAt:date,merchant:merchant||undefined,expenseId})),prior=JSON.parse(localStorage.getItem(PURCHASES)||"[]") as unknown[];localStorage.setItem(PURCHASES,JSON.stringify([...stock,...prior]));setApp(next);setMessage(stock.length?"已入帳，並保存 "+stock.length+" 項存貨資料":"已將整張單入帳");setSaving(false)}catch{setSaving(false);setMessage("暫時未能保存，請勿離開並再試")}}
 return <main style={s.page}><section style={s.shell}><div style={s.top}><Link href="/" style={s.back}>‹ My Expenses</Link><b style={s.badge}>SHOPPING INPUT · BETA</b></div><h1 style={s.title}>智能購物入帳</h1><p style={s.lead}>影紙單、揀付款截圖或淘寶訂單。相片只會在這一頁預覽，唔會保存到支出資料。</p>
 <article style={s.card}><h2 style={s.h2}>1. 加入購物憑證</h2><p style={s.muted}>紙單、付款成功畫面、淘寶訂單截圖都可以。</p><div style={s.choices}><label style={s.upload}>📷<strong>即刻影相</strong><input aria-label="即刻影相" type="file" accept="image/*" capture="environment" disabled={scanning} onChange={chooseFile} style={s.hidden}/></label><label style={s.upload}>▣<strong>揀截圖／相片</strong><input aria-label="揀截圖或相片" type="file" accept="image/*" onChange={chooseFile} style={s.hidden}/></label></div>{preview&&<><figure style={s.figure}><img src={preview} alt="購物憑證預覽" style={s.image}/><figcaption>{fileName}</figcaption></figure><p role="status" style={s.ocr}>{scanning?"正在自動辨認 "+scanProgress+"%":message}</p>{!scanning&&sourceFile&&<button type="button" onClick={()=>void scanReceipt(sourceFile)} style={s.remove}>重新辨認（選用）</button>}<p style={s.privacy}>只在此裝置辨認，不會上載相片；辨認結果由你確認後才入帳。</p>{ocrText&&<details style={s.details}><summary>查看辨認文字</summary><pre style={s.ocrRaw}>{ocrText}</pre></details>}</>}</article>
 <article style={s.card}><h2 style={s.h2}>2. 核對並入帳</h2><div style={s.amountRow}><select aria-label="貨幣" value={currency} onChange={event=>setCurrency(event.target.value as Currency)} style={s.currency}>{currencies.map(item=><option key={item}>{item}</option>)}</select><input aria-label="實付總額" inputMode="decimal" type="number" min="0" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="實付總額" style={s.amount}/></div>{currency!=="HKD"&&<p style={s.muted}>沿用已保存匯率：1 {currency} ≈ HK {rate.toFixed(4)}</p>}<button type="button" disabled={saving||!number||scanning} onClick={()=>void save()} style={s.save}>{saving?"正在保存…":number?`確認 ${currency} ${number.toLocaleString("en-HK")} 並入帳`:"請輸入實付總額"}</button><p style={s.status}>{message}</p></article>
 <details style={s.card}><summary style={s.h2}>其他資料（需要時才修改）</summary><div style={s.grid}><label style={s.label}>店舖／平台<input value={merchant} onChange={event=>setMerchant(event.target.value)} placeholder="例如：Fusion、淘寶" style={s.input}/></label><label style={s.label}>日期<input type="date" value={date} onChange={event=>setDate(event.target.value)} style={s.input}/></label><label style={s.label}>支出分類<select value={category} onChange={event=>setCategory(event.target.value)} style={s.input}>{categories.map(item=><option key={item.id}>{item.name}</option>)}</select></label></div>{items.length>0&&<div style={s.detected}><strong>已保留畀 Price Radar</strong>{items.map(item=><div key={item.id}>{item.name} × {item.quantity}{item.size?` · ${item.size}${item.unit}`:""}</div>)}</div>}{ocrText&&<details style={s.details}><summary>查看 OCR 文字</summary><pre style={s.ocrRaw}>{ocrText}</pre></details>}</details>
 <article style={s.info}><strong>最快入帳方式</strong><p>拍照或揀圖後自動辨認。只需核對實付總額再按一次確認；店舖及商品認到就自動保留畀 Price Radar。</p></article></section></main>
}
const s:Record<string,React.CSSProperties>={page:{minHeight:"100vh",background:"#f4f4f2",color:"#151515",padding:"18px 14px 70px",fontFamily:"-apple-system,BlinkMacSystemFont,'Segoe UI','Noto Sans TC',sans-serif"},shell:{maxWidth:720,margin:"0 auto"},top:{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18},back:{color:"#151515",textDecoration:"none",fontWeight:700},badge:{fontSize:10,letterSpacing:".08em",padding:"6px 9px",border:"1px solid #d8d8d2",borderRadius:999,background:"white"},title:{fontSize:34,lineHeight:1.05,margin:"0 0 8px"},lead:{margin:0,color:"#666",lineHeight:1.55,fontSize:14},card:{background:"white",border:"1px solid #deded8",borderRadius:20,padding:16,margin:"12px 0"},h2:{fontSize:18,margin:"0 0 5px"},muted:{color:"#777",fontSize:12,lineHeight:1.45,margin:"5px 0 0"},choices:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginTop:14},upload:{display:"grid",placeItems:"center",gap:6,border:"1.5px dashed #bdbdb4",borderRadius:16,padding:"18px 10px",background:"#fafaf8",cursor:"pointer",fontSize:13},hidden:{display:"none"},figure:{margin:"14px 0 0",fontSize:12,color:"#666"},image:{width:"100%",maxHeight:300,objectFit:"contain",borderRadius:14,border:"1px solid #e3e3dc",background:"#f8f8f5"},ocr:{width:"100%",border:0,borderRadius:12,padding:"12px",marginTop:12,background:"#e1f1e6",color:"#174c3c",fontWeight:800},privacy:{margin:"7px 2px 0",fontSize:11,color:"#6d7d76",lineHeight:1.4},details:{marginTop:10,fontSize:12,color:"#53645d"},ocrRaw:{whiteSpace:"pre-wrap",maxHeight:190,overflow:"auto",padding:10,borderRadius:10,background:"#f5f6f2",fontFamily:"inherit"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(135px,1fr))",gap:9,marginTop:11},label:{fontSize:11,fontWeight:700,color:"#666",display:"grid",gap:5},input:{width:"100%",border:"1px solid #d8d8d2",borderRadius:11,padding:"9px 10px",background:"white",color:"#111",fontSize:14},amountRow:{display:"grid",gridTemplateColumns:"110px 1fr",gap:10,marginTop:14},currency:{border:"1px solid #b8d7c8",borderRadius:14,padding:"12px",background:"#eef8f2",color:"#174c3c",fontSize:18,fontWeight:800},amount:{width:"100%",border:"2px solid #81c5a5",borderRadius:14,padding:"12px",fontSize:30,fontWeight:850,color:"#10241d",background:"white"},row:{display:"flex",justifyContent:"space-between",gap:12,alignItems:"flex-start"},detected:{marginTop:14,padding:12,borderRadius:12,background:"#f5f6f2",fontSize:12,lineHeight:1.7,color:"#456157"},remove:{position:"absolute",right:8,top:8,border:0,background:"transparent",color:"#9b3f3f",fontWeight:700,fontSize:12},save:{width:"100%",border:0,borderRadius:14,padding:"14px",marginTop:14,background:"#173f34",color:"white",fontSize:16,fontWeight:800},status:{margin:"10px 0 0",fontSize:12,lineHeight:1.45,color:"#476257"},info:{margin:"16px 0",padding:"13px 14px",borderRadius:16,background:"#e8f2eb",fontSize:12,lineHeight:1.5,color:"#355447"}};
