"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Currency = "HKD"|"CNY"|"TWD"|"JPY"|"KRW"|"THB"|"IDR"|"SGD"|"MYR"|"USD"|"EUR"|"GBP"|"CAD"|"AUD"|"NZD"|"PHP"|"VND";
type ExpenseType = "daily"|"travel";
type Category = { id:string; name:string; subcategories?:string[] };
type Expense = { id:string; amount:number; currency:Currency; hkdAmount:number; rate:number; categoryId:string; subcategory?:string; date:string; note:string; createdAt:number; expenseType:ExpenseType; tripName?:string };
type TripRates = Record<string,Partial<Record<Currency,number>>>;
type TripLastCurrencies = Record<string,Currency>;
type AppData = { version:3; expenses:Expense[]; categories:Category[]; rates:Record<Currency,number>; tripBudgets:Record<string,number>; tripRates:TripRates; tripLastCurrencies:TripLastCurrencies; settings:{baseCurrency:"HKD";rateUpdated:string;lastMode?:ExpenseType;lastTrip?:string} };
type Tab = "dashboard"|"records"|"categories"|"settings";

const DEFAULT_CATEGORIES:Category[]=["交通費","早餐","午餐","晚餐","買餸","日常消費","睇戲","電話費","上網費","其他"].map((name,i)=>({id:`cat-${i+1}`,name,...(name==="交通費"?{subcategories:["巴士","的士","地鐵"]}:{})}));
const DEFAULT_RATES:Record<Currency,number>={HKD:1,CNY:1.08,TWD:.245,JPY:.052,KRW:.0055,THB:.235,IDR:.00047,SGD:6.05,MYR:1.84,USD:7.8,EUR:9.1,GBP:10.55,CAD:5.65,AUD:5.1,NZD:4.65,PHP:.137,VND:.0003};
const CURRENCIES:{code:Currency;label:string}[]=[["HKD","港幣"],["CNY","人民幣"],["TWD","新台幣"],["JPY","日圓"],["KRW","韓圜"],["THB","泰銖"],["IDR","印尼盾"],["SGD","新加坡元"],["MYR","馬來西亞令吉"],["USD","美元"],["EUR","歐元"],["GBP","英鎊"],["CAD","加拿大元"],["AUD","澳元"],["NZD","紐西蘭元"],["PHP","菲律賓披索"],["VND","越南盾"]].map(([code,label])=>({code:code as Currency,label}));
const today=()=>new Date().toLocaleDateString("en-CA");
const monthKey=(d:string)=>d.slice(0,7);
const makeId=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;
const whole=(c:Currency)=>["KRW","JPY","IDR","VND"].includes(c);
const money=(n:number,c:Currency="HKD")=>new Intl.NumberFormat("en-HK",{style:"currency",currency:c,maximumFractionDigits:whole(c)?0:2}).format(n);
const originalMoney=(n:number,c:Currency)=>`${c} ${new Intl.NumberFormat("en-HK",{maximumFractionDigits:whole(c)?0:2}).format(n)}`;
const shortDate=(d:string)=>new Intl.DateTimeFormat("zh-HK",{month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`));
const monthTitle=(m:string)=>{const[y,mo]=m.split("-");return `${y}年 ${Number(mo)}月`};
const DB_NAME="antony-expenses-db",DB_STORE="app-data",DB_KEY="current";

function normalizeData(input:Partial<AppData>&{expenses?:Array<Partial<Expense>>}):AppData{
  const expenses=(input.expenses||[]).map(raw=>({...raw,expenseType:raw.expenseType==="travel"&&raw.tripName?.trim()?"travel":"daily",tripName:raw.expenseType==="travel"&&raw.tripName?.trim()?raw.tripName.trim():undefined})) as Expense[];
  const tripRates:TripRates={...(input.tripRates||{})};
  expenses.filter(e=>e.expenseType==="travel"&&e.tripName).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt-b.createdAt).forEach(e=>{const name=e.tripName!;tripRates[name]||={};if(tripRates[name][e.currency]==null)tripRates[name][e.currency]=e.rate});
  const tripLastCurrencies:TripLastCurrencies={...(input.tripLastCurrencies||{})};
  expenses.filter(e=>e.expenseType==="travel"&&e.tripName).sort((a,b)=>a.createdAt-b.createdAt).forEach(e=>{if(!input.tripLastCurrencies?.[e.tripName!])tripLastCurrencies[e.tripName!]=e.currency});
  return{version:3,expenses,categories:input.categories||DEFAULT_CATEGORIES,rates:{...DEFAULT_RATES,...input.rates},tripBudgets:{...(input.tripBudgets||{})},tripRates,tripLastCurrencies,settings:{baseCurrency:"HKD",rateUpdated:input.settings?.rateUpdated||"預設參考匯率",lastMode:input.settings?.lastMode==="travel"?"travel":"daily",lastTrip:input.settings?.lastTrip||""}};
}
function openDatabase():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function readDatabase():Promise<AppData|null>{const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,"readonly"),r=tx.objectStore(DB_STORE).get(DB_KEY);r.onsuccess=()=>resolve(r.result?normalizeData(r.result):null);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()})}
async function writeDatabase(data:AppData):Promise<void>{const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,"readwrite");tx.objectStore(DB_STORE).put(data,DB_KEY);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function readLegacyData():AppData|null{try{const ex=localStorage.getItem("antony-expenses"),cats=localStorage.getItem("antony-categories"),rates=localStorage.getItem("antony-rates");if(!ex&&!cats&&!rates)return null;return normalizeData({expenses:ex?JSON.parse(ex):[],categories:cats?JSON.parse(cats):DEFAULT_CATEGORIES,rates:rates?JSON.parse(rates):DEFAULT_RATES,tripBudgets:JSON.parse(localStorage.getItem("antony-trip-budgets")||"{}"),tripRates:JSON.parse(localStorage.getItem("antony-trip-rates")||"{}"),tripLastCurrencies:JSON.parse(localStorage.getItem("antony-trip-last-currencies")||"{}"),settings:{baseCurrency:"HKD",rateUpdated:localStorage.getItem("antony-rate-updated")||"預設參考匯率",lastMode:localStorage.getItem("antony-last-mode")==="travel"?"travel":"daily",lastTrip:localStorage.getItem("antony-last-trip")||""}})}catch{return null}}
function mirror(data:AppData){try{localStorage.setItem("antony-expenses",JSON.stringify(data.expenses));localStorage.setItem("antony-categories",JSON.stringify(data.categories));localStorage.setItem("antony-rates",JSON.stringify(data.rates));localStorage.setItem("antony-trip-budgets",JSON.stringify(data.tripBudgets));localStorage.setItem("antony-trip-rates",JSON.stringify(data.tripRates));localStorage.setItem("antony-trip-last-currencies",JSON.stringify(data.tripLastCurrencies));localStorage.setItem("antony-rate-updated",data.settings.rateUpdated);localStorage.setItem("antony-last-mode",data.settings.lastMode||"daily");localStorage.setItem("antony-last-trip",data.settings.lastTrip||"")}catch{/* IndexedDB remains primary */}}
function download(content:string,name:string,type:string){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvCell(value:string|number|undefined){return `"${String(value??"").replaceAll('"','""')}"`}
async function fetchRate(currency:Currency,fallback:number){if(currency==="HKD")return 1;try{const response=await fetch("https://open.er-api.com/v6/latest/HKD"),data=await response.json(),value=Number(data?.rates?.[currency]);if(!response.ok||!value)throw new Error();return 1/value}catch{return fallback}}

export default function Home(){
  const[ready,setReady]=useState(false),[tab,setTab]=useState<Tab>("dashboard"),[mode,setMode]=useState<ExpenseType>("daily"),[dailyScope,setDailyScope]=useState<"daily"|"all">("daily"),[selectedTrip,setSelectedTrip]=useState("");
  const[categories,setCategories]=useState<Category[]>(DEFAULT_CATEGORIES),[expenses,setExpenses]=useState<Expense[]>([]),[rates,setRates]=useState(DEFAULT_RATES),[tripBudgets,setTripBudgets]=useState<Record<string,number>>({}),[tripRates,setTripRates]=useState<TripRates>({}),[tripLastCurrencies,setTripLastCurrencies]=useState<TripLastCurrencies>({}),[rateUpdated,setRateUpdated]=useState("預設參考匯率");
  const[month,setMonth]=useState(today().slice(0,7)),[editorOpen,setEditorOpen]=useState(false),[editing,setEditing]=useState<Expense|null>(null),[categoryModal,setCategoryModal]=useState<Category|null|"new">(null),[toast,setToast]=useState("");const importRef=useRef<HTMLInputElement>(null);
  const tripNames=useMemo(()=>[...new Set(expenses.filter(e=>e.expenseType==="travel"&&e.tripName).map(e=>e.tripName!))].sort((a,b)=>a.localeCompare(b,"zh-HK")),[expenses]);
  useEffect(()=>{let active=true;(async()=>{let saved:AppData|null=null;try{saved=await readDatabase()}catch{}if(!saved){saved=readLegacyData();if(saved)try{await writeDatabase(saved)}catch{}}if(active&&saved){const savedTrips=[...new Set(saved.expenses.filter(e=>e.expenseType==="travel"&&e.tripName).map(e=>e.tripName!))].sort((a,b)=>a.localeCompare(b,"zh-HK"));setCategories(saved.categories.map(c=>c.id==="cat-1"&&!c.subcategories?{...c,subcategories:["巴士","的士","地鐵"]}:c));setExpenses(saved.expenses);setRates(saved.rates);setTripBudgets(saved.tripBudgets);setTripRates(saved.tripRates);setTripLastCurrencies(saved.tripLastCurrencies);setRateUpdated(saved.settings.rateUpdated);setMode(saved.settings.lastMode||"daily");setSelectedTrip(savedTrips.includes(saved.settings.lastTrip||"")?saved.settings.lastTrip!:(savedTrips[0]||""))}if(active)setReady(true)})();return()=>{active=false}},[]);
  useEffect(()=>{if(!ready)return;const data:AppData={version:3,expenses,categories,rates,tripBudgets,tripRates,tripLastCurrencies,settings:{baseCurrency:"HKD",rateUpdated,lastMode:mode,lastTrip:selectedTrip}};mirror(data);writeDatabase(data).catch(()=>notify("資料庫暫時未能寫入，已保存後備副本"))},[ready,expenses,categories,rates,tripBudgets,tripRates,tripLastCurrencies,rateUpdated,mode,selectedTrip]);
  const visible=useMemo(()=>{const list=mode==="daily"?expenses.filter(e=>monthKey(e.date)===month&&(dailyScope==="all"||e.expenseType!=="travel")):expenses.filter(e=>e.expenseType==="travel"&&e.tripName===selectedTrip);return list.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)},[expenses,mode,month,dailyScope,selectedTrip]);
  const total=visible.reduce((s,e)=>s+e.hkdAmount,0);
  const breakdown=useMemo(()=>categories.map(c=>({...c,total:visible.filter(e=>e.categoryId===c.id).reduce((s,e)=>s+e.hkdAmount,0)})).filter(c=>c.total>0).sort((a,b)=>b.total-a.total),[categories,visible]);
  const tripTotals=useMemo(()=>tripNames.map(name=>({name,total:expenses.filter(e=>e.expenseType==="travel"&&e.tripName===name).reduce((s,e)=>s+e.hkdAmount,0)})),[tripNames,expenses]);
  function notify(msg:string){setToast(msg);window.setTimeout(()=>setToast(""),2200)}
  function fullData():AppData{return{version:3,expenses,categories,rates,tripBudgets,tripRates,tripLastCurrencies,settings:{baseCurrency:"HKD",rateUpdated,lastMode:mode,lastTrip:selectedTrip}}}
  function saveExpense(data:Omit<Expense,"id"|"createdAt">){if(data.expenseType==="travel"&&data.tripName){const name=data.tripName.trim();setTripRates(current=>current[name]?.[data.currency]!=null?current:{...current,[name]:{...(current[name]||{}),[data.currency]:data.rate}});if(!editing)setTripLastCurrencies(current=>({...current,[name]:data.currency}));setSelectedTrip(name);setMode("travel")}if(editing)setExpenses(v=>v.map(e=>e.id===editing.id?{...e,...data}:e));else setExpenses(v=>[{...data,id:makeId(),createdAt:Date.now()},...v]);setEditorOpen(false);notify(editing?"支出已更新":"支出已儲存")}
  function deleteExpense(id:string){if(confirm("確定刪除這筆支出？")){setExpenses(v=>v.filter(e=>e.id!==id));setEditorOpen(false);notify("支出已刪除")}}
  function shiftMonth(delta:number){const[y,m]=month.split("-").map(Number),d=new Date(y,m-1+delta,1);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`)}
  async function refreshRates(){notify("正在更新匯率…");try{const response=await fetch("https://open.er-api.com/v6/latest/HKD"),data=await response.json();if(!response.ok||!data?.rates)throw new Error();setRates(Object.fromEntries(CURRENCIES.map(({code})=>[code,code==="HKD"?1:data.rates[code]?1/data.rates[code]:rates[code]])) as Record<Currency,number>);setRateUpdated(`更新於 ${new Date().toLocaleTimeString("zh-HK",{hour:"2-digit",minute:"2-digit"})}`);notify("自動匯率已更新")}catch{notify("未能連線，繼續使用現有匯率")}}
  function exportData(){download(JSON.stringify({app:"My Expenses",exportedAt:new Date().toISOString(),currencies:CURRENCIES,data:fullData()},null,2),`my-expenses-backup-${today()}.json`,"application/json");notify("完整備份已匯出")}
  function exportTripJson(){if(!selectedTrip)return notify("請先選擇行程");const data={version:3,kind:"trip",tripName:selectedTrip,expenses:expenses.filter(e=>e.expenseType==="travel"&&e.tripName===selectedTrip),categories,rates,tripBudgets:{[selectedTrip]:tripBudgets[selectedTrip]||0},tripRates:{[selectedTrip]:tripRates[selectedTrip]||{}},tripLastCurrencies:{[selectedTrip]:tripLastCurrencies[selectedTrip]},settings:{baseCurrency:"HKD",rateUpdated}};download(JSON.stringify({app:"My Expenses",exportedAt:new Date().toISOString(),data},null,2),`my-expenses-${selectedTrip}-${today()}.json`,"application/json");notify("行程 JSON 已匯出")}
  function exportTripCsv(){if(!selectedTrip)return notify("請先選擇行程");const header=["日期","旅程","分類","細分類","備註","原幣","原金額","當時匯率","HKD 金額","旅程預算"],rows=expenses.filter(e=>e.expenseType==="travel"&&e.tripName===selectedTrip).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt-b.createdAt).map(e=>[e.date,e.tripName,categories.find(c=>c.id===e.categoryId)?.name||"其他",e.subcategory,e.note,e.currency,e.amount,e.rate,e.hkdAmount,tripBudgets[selectedTrip]||0].map(csvCell).join(","));download(`\uFEFF${header.map(csvCell).join(",")}\n${rows.join("\n")}`,`my-expenses-${selectedTrip}-${today()}.csv`,"text/csv;charset=utf-8");notify("行程 CSV 已匯出")}
  async function importData(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const parsed=JSON.parse(await file.text()),raw=parsed?.data||parsed;if(!Array.isArray(raw.expenses)||!Array.isArray(raw.categories)||!raw.rates)throw new Error();const restored=normalizeData(raw);if(raw.kind==="trip"||raw.tripName){const name=String(raw.tripName||restored.expenses[0]?.tripName||"").trim();if(!name)throw new Error();setExpenses(current=>{const ids=new Set(restored.expenses.map(e=>e.id));return[...current.filter(e=>!ids.has(e.id)),...restored.expenses]});setCategories(current=>[...current,...restored.categories.filter(c=>!current.some(old=>old.id===c.id))]);setRates(current=>({...current,...restored.rates}));setTripBudgets(current=>({...current,[name]:restored.tripBudgets[name]||0}));setTripRates(current=>({...current,[name]:restored.tripRates[name]||{}}));setTripLastCurrencies(current=>({...current,...(restored.tripLastCurrencies[name]?{[name]:restored.tripLastCurrencies[name]}:{})}));setSelectedTrip(name);setMode("travel");notify("單一行程已匯入")}else{await writeDatabase(restored);mirror(restored);setExpenses(restored.expenses);setCategories(restored.categories);setRates(restored.rates);setTripBudgets(restored.tripBudgets);setTripRates(restored.tripRates);setTripLastCurrencies(restored.tripLastCurrencies);setRateUpdated(restored.settings.rateUpdated);setMode(restored.settings.lastMode||"daily");const restoredTrips=[...new Set(restored.expenses.filter(e=>e.expenseType==="travel"&&e.tripName).map(e=>e.tripName!))];setSelectedTrip(restoredTrips.includes(restored.settings.lastTrip||"")?restored.settings.lastTrip!:(restoredTrips[0]||""));setMonth(today().slice(0,7));notify("所有資料已完整還原")}}catch{notify("備份檔案格式不正確")}}
  if(!ready)return <main className="loading">My Expenses</main>;
  return <main className="app-shell"><div className="app-frame"><header className="topbar"><div><p className="eyebrow">MY EXPENSES</p><h1>{tab==="dashboard"?"你好":tab==="records"?"支出記錄":tab==="categories"?"支出分類":"設定"}</h1></div><div className="avatar">$</div></header>
    {(tab==="dashboard"||tab==="records")&&<ModeBar mode={mode} setMode={setMode} tripNames={tripNames} selectedTrip={selectedTrip} setSelectedTrip={setSelectedTrip}/>}
    {tab==="dashboard"&&<Dashboard mode={mode} dailyScope={dailyScope} setDailyScope={setDailyScope} month={month} selectedTrip={selectedTrip} total={total} budget={tripBudgets[selectedTrip]||0} expenses={visible} categories={categories} breakdown={breakdown} tripTotals={tripTotals} shiftMonth={shiftMonth} setBudget={value=>selectedTrip&&setTripBudgets(v=>({...v,[selectedTrip]:value}))} edit={e=>{setEditing(e);setEditorOpen(true)}} exportJson={exportTripJson} exportCsv={exportTripCsv}/>}
    {tab==="records"&&<Records expenses={mode==="daily"?expenses.filter(e=>e.expenseType!=="travel"):visible} categories={categories} edit={e=>{setEditing(e);setEditorOpen(true)}}/>}
    {tab==="categories"&&<Categories categories={categories} expenses={expenses} open={setCategoryModal}/>}
    {tab==="settings"&&<Settings rates={rates} updated={rateUpdated} setRates={setRates} refresh={refreshRates} exportData={exportData} importData={()=>importRef.current?.click()}/>}
    <nav className="bottom-nav" aria-label="主要導覽"><NavButton active={tab==="dashboard"} icon="▦" label="總覽" onClick={()=>setTab("dashboard")}/><NavButton active={tab==="records"} icon="≡" label="記錄" onClick={()=>setTab("records")}/><button className="add-button" onClick={()=>{setEditing(null);setEditorOpen(true)}} aria-label="新增支出">＋</button><NavButton active={tab==="categories"} icon="◫" label="分類" onClick={()=>setTab("categories")}/><NavButton active={tab==="settings"} icon="⚙" label="設定" onClick={()=>setTab("settings")}/></nav></div>
    {editorOpen&&<ExpenseEditor categories={categories} rates={rates} tripRates={tripRates} tripLastCurrencies={tripLastCurrencies} expense={editing} defaultType={mode} defaultTrip={selectedTrip} recent={expenses} notify={notify} addCategory={(name,subs)=>{if(categories.some(c=>c.name===name)){notify("已有相同名稱的分類");return null}const category={id:makeId(),name,subcategories:subs};setCategories(v=>[...v,category]);notify("分類已儲存");return category}} onClose={()=>setEditorOpen(false)} onSave={saveExpense} onDelete={editing?()=>deleteExpense(editing.id):undefined}/>}
    {categoryModal&&<CategoryEditor value={categoryModal==="new"?null:categoryModal} onClose={()=>setCategoryModal(null)} onSave={(name,subs)=>{if(categories.some(c=>c.name===name&&(categoryModal==="new"||c.id!==categoryModal.id))){notify("已有相同名稱的分類");return}if(categoryModal==="new")setCategories(v=>[...v,{id:makeId(),name,subcategories:subs}]);else setCategories(v=>v.map(c=>c.id===categoryModal.id?{...c,name,subcategories:subs}:c));setCategoryModal(null);notify("分類已儲存")}} onDelete={categoryModal==="new"?undefined:()=>{if(expenses.some(e=>e.categoryId===categoryModal.id))return notify("此分類仍有支出，不能刪除");setCategories(v=>v.filter(c=>c.id!==categoryModal.id));setCategoryModal(null);notify("分類已刪除")}}/>}
    <input ref={importRef} className="visually-hidden" type="file" accept="application/json,.json" onChange={importData}/>{toast&&<div className="toast">{toast}</div>}</main>
}

function ModeBar({mode,setMode,tripNames,selectedTrip,setSelectedTrip}:{mode:ExpenseType;setMode:(v:ExpenseType)=>void;tripNames:string[];selectedTrip:string;setSelectedTrip:(v:string)=>void}){return <section className="content mode-area"><div className="mode-switch"><button className={mode==="daily"?"selected":""} onClick={()=>setMode("daily")}>日常</button><button className={mode==="travel"?"selected":""} onClick={()=>{if(!selectedTrip&&tripNames[0])setSelectedTrip(tripNames[0]);setMode("travel")}}>旅行</button></div>{mode==="travel"&&<select className="trip-select" value={selectedTrip} onChange={e=>setSelectedTrip(e.target.value)}><option value="">新增支出以建立行程</option>{tripNames.map(name=><option key={name}>{name}</option>)}</select>}</section>}
type BreakdownItem=Category&{total:number};
function Dashboard({mode,dailyScope,setDailyScope,month,selectedTrip,total,budget,expenses,categories,breakdown,tripTotals,shiftMonth,setBudget,edit,exportJson,exportCsv}:{mode:ExpenseType;dailyScope:"daily"|"all";setDailyScope:(v:"daily"|"all")=>void;month:string;selectedTrip:string;total:number;budget:number;expenses:Expense[];categories:Category[];breakdown:BreakdownItem[];tripTotals:{name:string;total:number}[];shiftMonth:(v:number)=>void;setBudget:(v:number)=>void;edit:(e:Expense)=>void;exportJson:()=>void;exportCsv:()=>void}){const remaining=budget-total,percent=budget?total/budget*100:0;return <section className="content">
  {mode==="daily"?<><div className="month-switch"><button onClick={()=>shiftMonth(-1)}>‹</button><strong>{monthTitle(month)}</strong><button onClick={()=>shiftMonth(1)}>›</button></div><div className="scope-switch"><button className={dailyScope==="daily"?"selected":""} onClick={()=>setDailyScope("daily")}>只計日常</button><button className={dailyScope==="all"?"selected":""} onClick={()=>setDailyScope("all")}>包括旅行</button></div></>:<div className="trip-heading"><strong>{selectedTrip||"尚未建立行程"}</strong><span>{expenses.length} 筆支出</span></div>}
  <article className="total-card"><span>{mode==="daily"?"本月總支出":"行程總支出"}</span><strong>{money(total)}</strong><small>{expenses.length} 筆支出 · 全部已換算港幣</small><div className="soft-orb"/></article>
  {mode==="travel"&&selectedTrip&&<article className={`card budget-card ${budget&&remaining<0?"over":""}`}><div className="budget-head"><div><h2>旅程預算</h2><p>{budget?(remaining>=0?`尚餘 ${money(remaining)}`:`已超支 ${money(-remaining)}`):"設定 HKD 預算以追蹤進度"}</p></div><label>HK$ <input type="number" min="0" step="any" value={budget||""} placeholder="0" onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label></div><div className="budget-progress"><i style={{width:`${Math.min(percent,100)}%`}}/></div><small>{budget?`已使用 ${percent.toFixed(1)}%${remaining<0?" · 超支":""}`:"尚未設定預算"}</small></article>}
  {mode==="travel"&&tripTotals.length>1&&<><div className="section-title"><h2>行程比較</h2><span>{tripTotals.length} 個行程</span></div><article className="card trip-compare">{tripTotals.map(t=><div key={t.name} className={t.name===selectedTrip?"current":""}><span>{t.name}</span><strong>{money(t.total)}</strong></div>)}</article></>}
  <div className="section-title"><h2>分類支出</h2><span>{breakdown.length} 個分類</span></div><article className="card category-summary">{breakdown.length?breakdown.map((c,i)=><div className="category-row" key={c.id}><div className={`category-icon tone-${i%4}`}>{c.name.slice(0,1)}</div><div className="category-data"><div><strong>{c.name}</strong><span>{money(c.total)}</span></div><div className="bar"><i style={{width:`${total?c.total/total*100:0}%`}}/></div><small>{total?(c.total/total*100).toFixed(1):0}%</small></div></div>):<Empty text={mode==="daily"?"今個月未有支出":"此行程未有支出"}/>}</article>
  <div className="section-title"><h2>最近支出</h2></div><article className="card record-list">{expenses.slice(0,5).map(e=><ExpenseRow key={e.id} e={e} category={categories.find(c=>c.id===e.categoryId)} onClick={()=>edit(e)}/>)}{!expenses.length&&<Empty text="撳下面 ＋ 新增第一筆支出"/>}</article>
  {mode==="travel"&&selectedTrip&&<details className="card trip-export-panel"><summary>備份與匯出</summary><div className="trip-export"><button onClick={exportJson}>備份 JSON</button><button onClick={exportCsv}>匯出 CSV</button></div></details>}</section>}
function Records({expenses,categories,edit}:{expenses:Expense[];categories:Category[];edit:(e:Expense)=>void}){const groups=expenses.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).reduce<Record<string,Expense[]>>((o,e)=>{(o[e.date]||=[]).push(e);return o},{});return <section className="content records-page">{Object.entries(groups).map(([date,list])=><div key={date}><div className="day-heading"><strong>{date===today()?"今日":shortDate(date)}</strong><span>{money(list.reduce((s,e)=>s+e.hkdAmount,0))}</span></div><article className="card record-list">{list.map(e=><ExpenseRow key={e.id} e={e} category={categories.find(c=>c.id===e.categoryId)} onClick={()=>edit(e)}/>)}</article></div>)}{!expenses.length&&<article className="card"><Empty text="暫時未有支出記錄"/></article>}</section>}
function Categories({categories,expenses,open}:{categories:Category[];expenses:Expense[];open:(c:Category|"new")=>void}){return <section className="content"><p className="page-lead">管理分類及其細分類。</p><article className="card manage-list">{categories.map(c=><button key={c.id} onClick={()=>open(c)}><span className="category-icon">{c.name.slice(0,1)}</span><span><strong>{c.name}</strong><small>{c.subcategories?.length?`${c.subcategories.join(" · ")} · `:""}{expenses.filter(e=>e.categoryId===c.id).length} 筆記錄</small></span><b>›</b></button>)}</article><button className="secondary-action" onClick={()=>open("new")}>＋ 新增分類</button></section>}
function Settings({rates,updated,setRates,refresh,exportData,importData}:{rates:Record<Currency,number>;updated:string;setRates:React.Dispatch<React.SetStateAction<Record<Currency,number>>>;refresh:()=>void;exportData:()=>void;importData:()=>void}){return <section className="content"><article className="card settings-card"><div className="setting-title"><div><h2>參考匯率</h2><p>1 單位外幣可兌換的港幣</p></div><button onClick={refresh}>自動更新</button></div>{CURRENCIES.filter(c=>c.code!=="HKD").map(c=><label className="rate-line" key={c.code}><span><strong>{c.code}</strong><small>{c.label}</small></span><div><input type="number" step=".000001" value={rates[c.code]} onChange={e=>setRates(v=>({...v,[c.code]:Number(e.target.value)}))}/><em>HKD</em></div></label>)}<small className="updated">{updated} · 網絡失敗時使用</small></article><article className="card about-card"><h2>資料備份</h2><p>包含全部支出、分類、貨幣、參考匯率、旅程預算、行程鎖定匯率及設定。完整備份或單一行程 JSON 都可匯入。</p><div className="backup-actions"><button onClick={exportData}>匯出完整備份</button><button onClick={importData}>匯入 JSON</button></div></article><article className="card about-card"><h2>資料保存</h2><p>資料使用這部裝置瀏覽器的 IndexedDB 保存，並建立 localStorage 後備副本。清除 Safari 網站資料會同時刪除記錄。</p></article><article className="card about-card"><h2>Base Currency</h2><p>HKD 港幣 · 所有統計均以港幣顯示</p></article></section>}

function ExpenseEditor({categories,rates,tripRates,tripLastCurrencies,expense,defaultType,defaultTrip,recent,notify,addCategory,onClose,onSave,onDelete}:{categories:Category[];rates:Record<Currency,number>;tripRates:TripRates;tripLastCurrencies:TripLastCurrencies;expense:Expense|null;defaultType:ExpenseType;defaultTrip:string;recent:Expense[];notify:(v:string)=>void;addCategory:(name:string,subs:string[])=>Category|null;onClose:()=>void;onSave:(e:Omit<Expense,"id"|"createdAt">)=>void;onDelete?:()=>void}){
  const initialCurrency=expense?.currency||(!expense&&defaultType==="travel"&&defaultTrip?tripLastCurrencies[defaultTrip]:undefined)||"HKD",initialRate=expense?.rate||tripRates[defaultTrip]?.[initialCurrency]||rates[initialCurrency];
  const[amount,setAmount]=useState(expense?.amount.toString()||""),[currency,setCurrency]=useState<Currency>(initialCurrency),[rate,setRate]=useState(initialRate),[expenseType,setExpenseType]=useState<ExpenseType>(expense?.expenseType||defaultType),[tripName,setTripName]=useState(expense?.tripName||defaultTrip),[loading,setLoading]=useState(false),[categoryId,setCategoryId]=useState(expense?.categoryId||""),[subcategory,setSubcategory]=useState(expense?.subcategory||""),[date,setDate]=useState(expense?.date||today()),[note,setNote]=useState(expense?.note||""),[addingCategory,setAddingCategory]=useState(false);
  const trip=tripName.trim(),locked=expenseType==="travel"&&trip?tripRates[trip]?.[currency]:undefined,popular=[...new Set(recent.map(e=>e.categoryId))].map(id=>categories.find(c=>c.id===id)).filter(Boolean).slice(0,4) as Category[],ordered=[...popular,...categories.filter(c=>!popular.some(p=>p.id===c.id))],selected=categories.find(c=>c.id===categoryId),hkd=(Number(amount)||0)*(locked??rate);
  async function chooseCurrency(next:Currency,type=expenseType,name=trip){setCurrency(next);if(expense&&next===expense.currency&&type===expense.expenseType&&name===expense.tripName){setRate(expense.rate);return}const fixed=type==="travel"&&name?tripRates[name]?.[next]:undefined;if(fixed!=null){setRate(fixed);return}setLoading(true);const latest=await fetchRate(next,rates[next]);setRate(latest);setLoading(false);if(latest===rates[next]&&next!=="HKD")notify("未能取得最新匯率，已使用保存的參考匯率")}
  function applyTripCurrency(name:string){const preferred=tripLastCurrencies[name]||currency;void chooseCurrency(preferred,"travel",name)}
  function submit(e:FormEvent){e.preventDefault();if(!amount||Number(amount)<=0||!categoryId||loading||(expenseType==="travel"&&!trip))return;const finalRate=locked??rate;onSave({amount:Number(amount),currency,hkdAmount:Number(amount)*finalRate,rate:finalRate,categoryId,subcategory:subcategory||undefined,date,note:note.trim(),expenseType,tripName:expenseType==="travel"?trip:undefined})}
  return <><div className="modal-backdrop"><form className="sheet" onSubmit={submit}><div className="sheet-handle"/><div className="sheet-head"><button type="button" onClick={onClose}>取消</button><h2>{expense?"編輯支出":"新增支出"}</h2><button disabled={!amount||!categoryId||loading||(expenseType==="travel"&&!trip)}>儲存</button></div><div className="editor-mode mode-switch"><button type="button" className={expenseType==="daily"?"selected":""} onClick={()=>{setExpenseType("daily");void chooseCurrency(currency,"daily","")}}>日常</button><button type="button" className={expenseType==="travel"?"selected":""} onClick={()=>{setExpenseType("travel");if(trip)applyTripCurrency(trip)}}>旅行</button></div>
    {expenseType==="travel"&&<label className="form-line"><span>行程名稱</span><input value={tripName} onChange={e=>setTripName(e.target.value)} onBlur={()=>trip&&applyTripCurrency(trip)} placeholder="例如：釜山 2026" required/></label>}
    <div className="amount-entry"><select value={currency} onChange={e=>void chooseCurrency(e.target.value as Currency)}>{CURRENCIES.map(c=><option key={c.code}>{c.code}</option>)}</select><input autoFocus inputMode="decimal" type="number" min="0" step="any" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value)}/><small>{loading?"正在取得最新匯率…":`≈ ${money(hkd)} HKD`}</small></div>
    {currency!=="HKD"&&<label className="form-line"><span>匯率 {locked!=null&&<small>（行程已鎖定）</small>}</span><div className="inline-rate"><input type="number" step=".000001" value={locked??rate} disabled={locked!=null||loading} onChange={e=>setRate(Number(e.target.value))}/><small>HKD / {currency}</small></div></label>}
    <div className="form-block"><span>分類</span><div className="category-chips">{ordered.map((c,i)=><button type="button" className={categoryId===c.id?"selected":""} key={c.id} onClick={()=>{setCategoryId(c.id);setSubcategory("")}}>{i<popular.length&&<i>常用</i>}{c.name}</button>)}</div>{expenseType==="travel"&&<button className="inline-add-category" type="button" onClick={()=>setAddingCategory(true)}>＋ 新增分類</button>}</div>
    {selected?.subcategories?.length?<div className="form-block"><span>細分類 <small>選填</small></span><div className="category-chips"><button type="button" className={!subcategory?"selected":""} onClick={()=>setSubcategory("")}>不指定</button>{selected.subcategories.map(s=><button type="button" className={subcategory===s?"selected":""} key={s} onClick={()=>setSubcategory(s)}>{s}</button>)}</div></div>:null}
    <label className="form-line"><span>日期</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="form-block"><span>備註 <small>選填</small></span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：韓國旅行晚餐"/></label>{onDelete&&<button className="delete-button" type="button" onClick={onDelete}>刪除這筆支出</button>}</form></div>{addingCategory&&<CategoryEditor value={null} onClose={()=>setAddingCategory(false)} onSave={(name,subs)=>{const category=addCategory(name,subs);if(!category)return;setCategoryId(category.id);setSubcategory("");setAddingCategory(false)}}/>}</>
}
function CategoryEditor({value,onClose,onSave,onDelete}:{value:Category|null;onClose:()=>void;onSave:(n:string,s:string[])=>void;onDelete?:()=>void}){const[name,setName]=useState(value?.name||""),[subs,setSubs]=useState<string[]>(value?.subcategories||[]),[newSub,setNewSub]=useState("");function add(){const s=newSub.trim();if(s&&!subs.includes(s)){setSubs(v=>[...v,s]);setNewSub("")}}return <div className="modal-backdrop"><form className="mini-sheet" onSubmit={e=>{e.preventDefault();if(name.trim())onSave(name.trim(),subs)}}><div className="sheet-head"><button type="button" onClick={onClose}>取消</button><h2>{value?"編輯分類":"新增分類"}</h2><button disabled={!name.trim()}>儲存</button></div><label>分類名稱<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="輸入分類名稱"/></label><div className="subcategory-editor"><strong>細分類</strong><div className="subcategory-add"><input value={newSub} onChange={e=>setNewSub(e.target.value)} placeholder="例如：巴士"/><button type="button" onClick={add}>加入</button></div><div className="subcategory-list">{subs.map((s,i)=><span key={`${s}-${i}`}>{s}<button type="button" onClick={()=>setSubs(v=>v.filter((_,x)=>x!==i))}>×</button></span>)}</div></div>{onDelete&&<button type="button" className="delete-button" onClick={onDelete}>刪除分類</button>}</form></div>}
function ExpenseRow({e,category,onClick}:{e:Expense;category?:Category;onClick:()=>void}){return <button className="expense-row" onClick={onClick}><span className="category-icon">{category?.name.slice(0,1)||"其"}</span><span className="expense-main"><strong>{category?.name||"其他"}{e.subcategory?` · ${e.subcategory}`:""}</strong><small>{shortDate(e.date)}{e.tripName?` · ${e.tripName}`:""}{e.note?` · ${e.note}`:""}</small></span><span className="expense-money"><strong>{money(e.hkdAmount)}</strong>{e.currency!=="HKD"&&<small>{originalMoney(e.amount,e.currency)}</small>}</span></button>}
function NavButton({active,icon,label,onClick}:{active:boolean;icon:string;label:string;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}><i>{icon}</i><span>{label}</span></button>}
function Empty({text}:{text:string}){return <div className="empty"><div>✓</div><p>{text}</p></div>}
