"use client";

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { buildMonthlySummary, calculateExpression, newestSnapshot, previousMonthKey, settleBalances, splitAmount, SplitShare } from "./expense-math";

type Currency = "HKD"|"CNY"|"TWD"|"JPY"|"KRW"|"THB"|"IDR"|"SGD"|"MYR"|"USD"|"EUR"|"GBP"|"CAD"|"AUD"|"NZD"|"PHP"|"VND";
type ExpenseType = "daily"|"travel";
type Category = { id:string; name:string; subcategories?:string[] };
type TripMember = { memberId:string; name:string; active:boolean };
type TripSplit = { enabled:boolean; members:TripMember[]; lastPayerId:string };
type TripSplits = Record<string,TripSplit>;
type Expense = { id:string; amount:number; currency:Currency; hkdAmount:number; rate:number; categoryId:string; subcategory?:string; date:string; note:string; createdAt:number; expenseType:ExpenseType; tripName?:string; payerMemberId?:string; splitMemberIds?:string[]; splitShares?:SplitShare[] };
type TripRates = Record<string,Partial<Record<Currency,number>>>;
type TripLastCurrencies = Record<string,Currency>;
type ChartMode = "bar"|"donut";
type AppData = { version:5; updatedAt:number; expenses:Expense[]; categories:Category[]; rates:Record<Currency,number>; monthlyBudgets:Record<string,number>; tripBudgets:Record<string,number>; tripRates:TripRates; tripLastCurrencies:TripLastCurrencies; tripSplits:TripSplits; settings:{baseCurrency:"HKD";rateUpdated:string;lastMode?:ExpenseType;lastTrip?:string;chartMode?:ChartMode} };
type Tab = "dashboard"|"records"|"categories"|"settings";

const DEFAULT_CATEGORIES:Category[]=["交通費","早餐","午餐","晚餐","買餸","日常消費","睇戲","電話費","上網費","其他"].map((name,i)=>({id:`cat-${i+1}`,name,...(name==="交通費"?{subcategories:["巴士","的士","地鐵"]}:{})}));
const DEFAULT_RATES:Record<Currency,number>={HKD:1,CNY:1.08,TWD:.245,JPY:.052,KRW:.0055,THB:.235,IDR:.00047,SGD:6.05,MYR:1.84,USD:7.8,EUR:9.1,GBP:10.55,CAD:5.65,AUD:5.1,NZD:4.65,PHP:.137,VND:.0003};
const CURRENCIES:{code:Currency;label:string}[]=[["HKD","港幣"],["CNY","人民幣"],["TWD","新台幣"],["JPY","日圓"],["KRW","韓圜"],["THB","泰銖"],["IDR","印尼盾"],["SGD","新加坡元"],["MYR","馬來西亞令吉"],["USD","美元"],["EUR","歐元"],["GBP","英鎊"],["CAD","加拿大元"],["AUD","澳元"],["NZD","紐西蘭元"],["PHP","菲律賓披索"],["VND","越南盾"]].map(([code,label])=>({code:code as Currency,label}));
const today=()=>new Date().toLocaleDateString("en-CA");
const monthKey=(d:string)=>d.slice(0,7);
const makeId=()=>`${Date.now().toString(36)}-${Math.random().toString(36).slice(2,10)}`;
const whole=(c:Currency)=>["KRW","JPY","IDR","VND"].includes(c);
const money=(n:number,c:Currency="HKD")=>new Intl.NumberFormat("en-HK",{style:"currency",currency:c,maximumFractionDigits:whole(c)?0:2}).format(n);
const originalMoney=(n:number,c:Currency)=>`${c} ${new Intl.NumberFormat("en-HK",{maximumFractionDigits:whole(c)?0:2}).format(n)}`;
const shortDate=(d:string)=>new Intl.DateTimeFormat("zh-HK",{month:"short",day:"numeric"}).format(new Date(`${d}T12:00:00`));
const monthTitle=(m:string)=>{const[y,mo]=m.split("-");return `${y}年 ${Number(mo)}月`};
const monthClosed=(month:string)=>{const current=today().slice(0,7);if(month<current)return true;if(month>current)return false;const[y,m]=month.split("-").map(Number);return Number(today().slice(-2))===new Date(y,m,0).getDate()};
const DB_NAME="antony-expenses-db",DB_STORE="app-data",DB_KEY="current",LOCAL_SNAPSHOT_KEY="antony-app-data-v5";
const memberIdForTrip=(trip:string)=>`self-${Array.from(trip).reduce((hash,char)=>((hash<<5)-hash+char.charCodeAt(0))|0,0).toString(36).replace("-","n")}`;
const defaultTripSplit=(trip:string):TripSplit=>{const memberId=memberIdForTrip(trip);return{enabled:false,members:[{memberId,name:"我自己",active:true}],lastPayerId:memberId}};
const currencyDigits=(currency:Currency)=>whole(currency)?0:2;
const cleanSubcategories=(value:unknown)=>[...new Set((Array.isArray(value)?value:[]).map(item=>String(item).trim()).filter(Boolean))];
const categorySubcategories=(category:Category&{subCategories?:unknown;subs?:unknown})=>cleanSubcategories([
  ...(Array.isArray(category.subcategories)?category.subcategories:[]),
  ...(Array.isArray(category.subCategories)?category.subCategories:[]),
  ...(Array.isArray(category.subs)?category.subs:[]),
]);

function normalizeData(input:Partial<AppData>&{expenses?:Array<Partial<Expense>>}):AppData{
  const legacySettings=input.settings as AppData["settings"]&{tripBudgets?:Record<string,number>;tripRates?:TripRates;tripLastCurrencies?:TripLastCurrencies};
  const tripNames=[...new Set((input.expenses||[]).filter(raw=>raw.expenseType==="travel"&&raw.tripName?.trim()).map(raw=>raw.tripName!.trim()))];
  const tripSplits:TripSplits={};
  tripNames.forEach(name=>{const fallback=defaultTripSplit(name),raw=input.tripSplits?.[name];const members=(raw?.members||fallback.members).filter(member=>member?.memberId&&member?.name?.trim()).map(member=>({...member,name:member.name.trim(),active:member.active!==false}));const safeMembers=members.length?members:fallback.members;tripSplits[name]={enabled:raw?.enabled===true,members:safeMembers,lastPayerId:safeMembers.some(member=>member.memberId===raw?.lastPayerId)?raw!.lastPayerId:safeMembers[0].memberId}});
  const expenses=(input.expenses||[]).map(raw=>{const expenseType=raw.expenseType==="travel"&&raw.tripName?.trim()?"travel":"daily",tripName=expenseType==="travel"?raw.tripName!.trim():undefined;if(!tripName)return{...raw,expenseType,tripName:undefined,payerMemberId:undefined,splitMemberIds:undefined,splitShares:undefined};const config=tripSplits[tripName]||defaultTripSplit(tripName),self=config.members[0].memberId,payer=config.members.some(member=>member.memberId===raw.payerMemberId)?raw.payerMemberId!:self,selected=(raw.splitMemberIds||[]).filter(id=>config.members.some(member=>member.memberId===id)),splitMemberIds=selected.length?selected:[self],validShares=(raw.splitShares||[]).filter(share=>splitMemberIds.includes(share.memberId)&&Number.isFinite(share.amount));return{...raw,expenseType,tripName,payerMemberId:payer,splitMemberIds,splitShares:validShares.length===splitMemberIds.length?validShares:splitAmount(Number(raw.amount)||0,splitMemberIds,currencyDigits(raw.currency as Currency))}}) as Expense[];
  const tripRates:TripRates={...(legacySettings?.tripRates||{}),...(input.tripRates||{})};
  expenses.filter(e=>e.expenseType==="travel"&&e.tripName).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt-b.createdAt).forEach(e=>{const name=e.tripName!;tripRates[name]||={};if(tripRates[name][e.currency]==null)tripRates[name][e.currency]=e.rate});
  const tripLastCurrencies:TripLastCurrencies={...(legacySettings?.tripLastCurrencies||{}),...(input.tripLastCurrencies||{})};
  expenses.filter(e=>e.expenseType==="travel"&&e.tripName).sort((a,b)=>a.createdAt-b.createdAt).forEach(e=>{if(!input.tripLastCurrencies?.[e.tripName!])tripLastCurrencies[e.tripName!]=e.currency});
  const categories=(input.categories||DEFAULT_CATEGORIES).map(category=>({...category,subcategories:categorySubcategories(category)}));
  const updatedAt=Number.isFinite(input.updatedAt)?Number(input.updatedAt):expenses.reduce((latest,expense)=>Math.max(latest,Number(expense.createdAt)||0),0);
  return{version:5,updatedAt,expenses,categories,rates:{...DEFAULT_RATES,...input.rates},monthlyBudgets:{...(input.monthlyBudgets||{})},tripBudgets:{...(legacySettings?.tripBudgets||{}),...(input.tripBudgets||{})},tripRates,tripLastCurrencies,tripSplits,settings:{baseCurrency:"HKD",rateUpdated:input.settings?.rateUpdated||"預設參考匯率",lastMode:input.settings?.lastMode==="travel"?"travel":"daily",lastTrip:input.settings?.lastTrip||"",chartMode:input.settings?.chartMode==="donut"?"donut":"bar"}};
}
function openDatabase():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function readDatabase():Promise<AppData|null>{const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,"readonly"),r=tx.objectStore(DB_STORE).get(DB_KEY);r.onsuccess=()=>resolve(r.result?normalizeData(r.result):null);r.onerror=()=>reject(r.error);tx.oncomplete=()=>db.close()})}
async function writeDatabase(data:AppData):Promise<void>{const db=await openDatabase();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,"readwrite");tx.objectStore(DB_STORE).put(data,DB_KEY);tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
function readLegacyData():AppData|null{try{const ex=localStorage.getItem("antony-expenses"),cats=localStorage.getItem("antony-categories"),rates=localStorage.getItem("antony-rates");if(!ex&&!cats&&!rates)return null;return normalizeData({expenses:ex?JSON.parse(ex):[],categories:cats?JSON.parse(cats):DEFAULT_CATEGORIES,rates:rates?JSON.parse(rates):DEFAULT_RATES,tripBudgets:{...JSON.parse(localStorage.getItem("my-expenses-trip-budgets")||"{}"),...JSON.parse(localStorage.getItem("antony-trip-budgets")||"{}")},tripRates:{...JSON.parse(localStorage.getItem("my-expenses-trip-rates")||"{}"),...JSON.parse(localStorage.getItem("antony-trip-rates")||"{}")},tripLastCurrencies:JSON.parse(localStorage.getItem("antony-trip-last-currencies")||"{}"),tripSplits:JSON.parse(localStorage.getItem("antony-trip-splits")||"{}"),settings:{baseCurrency:"HKD",rateUpdated:localStorage.getItem("antony-rate-updated")||"預設參考匯率",lastMode:localStorage.getItem("antony-last-mode")==="travel"?"travel":"daily",lastTrip:localStorage.getItem("antony-last-trip")||""}})}catch{return null}}
function readLocalData():AppData|null{try{const snapshot=localStorage.getItem(LOCAL_SNAPSHOT_KEY);if(snapshot)return normalizeData(JSON.parse(snapshot))}catch{/* Fall through to legacy keys. */}return readLegacyData()}
function mirror(data:AppData):boolean{try{localStorage.setItem(LOCAL_SNAPSHOT_KEY,JSON.stringify(data));localStorage.setItem("antony-expenses",JSON.stringify(data.expenses));localStorage.setItem("antony-categories",JSON.stringify(data.categories));localStorage.setItem("antony-rates",JSON.stringify(data.rates));localStorage.setItem("antony-trip-budgets",JSON.stringify(data.tripBudgets));localStorage.setItem("antony-trip-rates",JSON.stringify(data.tripRates));localStorage.setItem("antony-trip-last-currencies",JSON.stringify(data.tripLastCurrencies));localStorage.setItem("antony-trip-splits",JSON.stringify(data.tripSplits));localStorage.setItem("antony-rate-updated",data.settings.rateUpdated);localStorage.setItem("antony-last-mode",data.settings.lastMode||"daily");localStorage.setItem("antony-last-trip",data.settings.lastTrip||"");return true}catch{return false}}
function download(content:string,name:string,type:string){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function csvCell(value:string|number|undefined){return `"${String(value??"").replaceAll('"','""')}"`}
async function fetchRate(currency:Currency,fallback:number){if(currency==="HKD")return 1;try{const response=await fetch("https://open.er-api.com/v6/latest/HKD"),data=await response.json(),value=Number(data?.rates?.[currency]);if(!response.ok||!value)throw new Error();return 1/value}catch{return fallback}}

export default function Home(){
  const[ready,setReady]=useState(false),[tab,setTab]=useState<Tab>("dashboard"),[mode,setMode]=useState<ExpenseType>("daily"),[dailyScope,setDailyScope]=useState<"daily"|"all">("daily"),[selectedTrip,setSelectedTrip]=useState("");
  const[categories,setCategories]=useState<Category[]>(DEFAULT_CATEGORIES),[expenses,setExpenses]=useState<Expense[]>([]),[rates,setRates]=useState(DEFAULT_RATES),[monthlyBudgets,setMonthlyBudgets]=useState<Record<string,number>>({}),[tripBudgets,setTripBudgets]=useState<Record<string,number>>({}),[tripRates,setTripRates]=useState<TripRates>({}),[tripLastCurrencies,setTripLastCurrencies]=useState<TripLastCurrencies>({}),[tripSplits,setTripSplits]=useState<TripSplits>({}),[rateUpdated,setRateUpdated]=useState("預設參考匯率");
  const[month,setMonth]=useState(today().slice(0,7)),[chartMode,setChartMode]=useState<ChartMode>("bar"),[editorOpen,setEditorOpen]=useState(false),[editing,setEditing]=useState<Expense|null>(null),[categoryModal,setCategoryModal]=useState<Category|null|"new">(null),[memberManagerOpen,setMemberManagerOpen]=useState(false),[toast,setToast]=useState("");const importRef=useRef<HTMLInputElement>(null),latestDataRef=useRef<AppData|null>(null),writeQueueRef=useRef<Promise<void>>(Promise.resolve()),announceSafeSaveRef=useRef(false);
  const tripNames=useMemo(()=>[...new Set(expenses.filter(e=>e.expenseType==="travel"&&e.tripName).map(e=>e.tripName!))].sort((a,b)=>a.localeCompare(b,"zh-HK")),[expenses]);
  useEffect(()=>{let active=true;(async()=>{const database=await readDatabase().catch(()=>null),local=readLocalData(),saved=newestSnapshot(database,local);if(saved){mirror(saved);await writeDatabase(saved).catch(()=>undefined)}if(active&&saved){const savedTrips=[...new Set(saved.expenses.filter(e=>e.expenseType==="travel"&&e.tripName).map(e=>e.tripName!))].sort((a,b)=>a.localeCompare(b,"zh-HK"));setCategories(saved.categories.map(c=>c.id==="cat-1"&&!c.subcategories?{...c,subcategories:["巴士","的士","地鐵"]}:c));setExpenses(saved.expenses);setRates(saved.rates);setMonthlyBudgets(saved.monthlyBudgets);setTripBudgets(saved.tripBudgets);setTripRates(saved.tripRates);setTripLastCurrencies(saved.tripLastCurrencies);setTripSplits(saved.tripSplits);setRateUpdated(saved.settings.rateUpdated);setMode(saved.settings.lastMode||"daily");setChartMode(saved.settings.chartMode||"bar");setSelectedTrip(savedTrips.includes(saved.settings.lastTrip||"")?saved.settings.lastTrip!:(savedTrips[0]||""))}if(active)setReady(true)})();return()=>{active=false}},[]);
  useEffect(()=>{if(!ready)return;const updatedAt=Math.max(Date.now(),(latestDataRef.current?.updatedAt||0)+1),data:AppData={version:5,updatedAt,expenses,categories,rates,monthlyBudgets,tripBudgets,tripRates,tripLastCurrencies,tripSplits,settings:{baseCurrency:"HKD",rateUpdated,lastMode:mode,lastTrip:selectedTrip,chartMode}};latestDataRef.current=data;const hasLocalBackup=mirror(data);writeQueueRef.current=writeQueueRef.current.catch(()=>undefined).then(()=>writeDatabase(data));writeQueueRef.current.then(()=>{if(announceSafeSaveRef.current&&latestDataRef.current?.updatedAt===updatedAt){announceSafeSaveRef.current=false;notify("資料已安全保存")}}).catch(()=>{if(announceSafeSaveRef.current){announceSafeSaveRef.current=false;notify(hasLocalBackup?"已保存後備副本":"未能保存，請立即匯出備份")}})},[ready,expenses,categories,rates,monthlyBudgets,tripBudgets,tripRates,tripLastCurrencies,tripSplits,rateUpdated,mode,selectedTrip,chartMode]);
  useEffect(()=>{const preserveLatest=()=>{if(latestDataRef.current)mirror(latestDataRef.current)},onVisibilityChange=()=>{if(document.visibilityState==="hidden")preserveLatest()};window.addEventListener("pagehide",preserveLatest);document.addEventListener("visibilitychange",onVisibilityChange);return()=>{window.removeEventListener("pagehide",preserveLatest);document.removeEventListener("visibilitychange",onVisibilityChange)}},[]);
  const visible=useMemo(()=>{const list=mode==="daily"?expenses.filter(e=>monthKey(e.date)===month&&(dailyScope==="all"||e.expenseType!=="travel")):expenses.filter(e=>e.expenseType==="travel"&&e.tripName===selectedTrip);return list.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt)},[expenses,mode,month,dailyScope,selectedTrip]);
  const total=visible.reduce((s,e)=>s+e.hkdAmount,0);
  const breakdown=useMemo(()=>categories.map(c=>({...c,total:visible.filter(e=>e.categoryId===c.id).reduce((s,e)=>s+e.hkdAmount,0)})).filter(c=>c.total>0).sort((a,b)=>b.total-a.total),[categories,visible]);
  const tripTotals=useMemo(()=>tripNames.map(name=>({name,total:expenses.filter(e=>e.expenseType==="travel"&&e.tripName===name).reduce((s,e)=>s+e.hkdAmount,0)})),[tripNames,expenses]);
  function notify(msg:string){setToast(msg);window.setTimeout(()=>setToast(""),2200)}
  function fullData():AppData{return{version:5,updatedAt:latestDataRef.current?.updatedAt||Date.now(),expenses,categories,rates,monthlyBudgets,tripBudgets,tripRates,tripLastCurrencies,tripSplits,settings:{baseCurrency:"HKD",rateUpdated,lastMode:mode,lastTrip:selectedTrip,chartMode}}}
  function saveExpense(data:Omit<Expense,"id"|"createdAt">){announceSafeSaveRef.current=true;if(data.expenseType==="travel"&&data.tripName){const name=data.tripName.trim();setTripRates(current=>current[name]?.[data.currency]!=null?current:{...current,[name]:{...(current[name]||{}),[data.currency]:data.rate}});if(!editing){setTripLastCurrencies(current=>({...current,[name]:data.currency}));if(data.payerMemberId)setTripSplits(current=>({...current,[name]:{...(current[name]||defaultTripSplit(name)),lastPayerId:data.payerMemberId!}}))}setSelectedTrip(name);setMode("travel")}if(editing)setExpenses(v=>v.map(e=>e.id===editing.id?{...e,...data}:e));else setExpenses(v=>[{...data,id:makeId(),createdAt:Date.now()},...v]);setEditorOpen(false);notify("正在安全保存…")}
  function deleteExpense(id:string){if(confirm("確定刪除這筆支出？")){setExpenses(v=>v.filter(e=>e.id!==id));setEditorOpen(false);notify("支出已刪除")}}
  function shiftMonth(delta:number){const[y,m]=month.split("-").map(Number),d=new Date(y,m-1+delta,1);setMonth(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`)}
  async function refreshRates(){notify("正在更新匯率…");try{const response=await fetch("https://open.er-api.com/v6/latest/HKD"),data=await response.json();if(!response.ok||!data?.rates)throw new Error();setRates(Object.fromEntries(CURRENCIES.map(({code})=>[code,code==="HKD"?1:data.rates[code]?1/data.rates[code]:rates[code]])) as Record<Currency,number>);setRateUpdated(`更新於 ${new Date().toLocaleTimeString("zh-HK",{hour:"2-digit",minute:"2-digit"})}`);notify("自動匯率已更新")}catch{notify("未能連線，繼續使用現有匯率")}}
  function exportData(){download(JSON.stringify({app:"My Expenses",exportedAt:new Date().toISOString(),currencies:CURRENCIES,data:fullData()},null,2),`my-expenses-backup-${today()}.json`,"application/json");notify("完整備份已匯出")}
  function exportTripJson(){if(!selectedTrip)return notify("請先選擇行程");const data={version:5,updatedAt:latestDataRef.current?.updatedAt||Date.now(),kind:"trip",tripName:selectedTrip,expenses:expenses.filter(e=>e.expenseType==="travel"&&e.tripName===selectedTrip),categories,rates,tripBudgets:{[selectedTrip]:tripBudgets[selectedTrip]||0},tripRates:{[selectedTrip]:tripRates[selectedTrip]||{}},tripLastCurrencies:{[selectedTrip]:tripLastCurrencies[selectedTrip]},tripSplits:{[selectedTrip]:tripSplits[selectedTrip]||defaultTripSplit(selectedTrip)},settings:{baseCurrency:"HKD",rateUpdated}};download(JSON.stringify({app:"My Expenses",exportedAt:new Date().toISOString(),data},null,2),`my-expenses-${selectedTrip}-${today()}.json`,"application/json");notify("行程 JSON 已匯出")}
  function exportTripCsv(){if(!selectedTrip)return notify("請先選擇行程");const config=tripSplits[selectedTrip]||defaultTripSplit(selectedTrip),memberName=(id?:string)=>config.members.find(member=>member.memberId===id)?.name||"我自己",header=["日期","旅程","分類","細分類","備註","原幣","原金額","當時匯率","HKD 金額","旅程預算","付款人","分擔成員","分擔方式","每人分擔明細"],rows=expenses.filter(e=>e.expenseType==="travel"&&e.tripName===selectedTrip).sort((a,b)=>a.date.localeCompare(b.date)||a.createdAt-b.createdAt).map(e=>[e.date,e.tripName,categories.find(c=>c.id===e.categoryId)?.name||"其他",e.subcategory,e.note,e.currency,e.amount,e.rate,e.hkdAmount,tripBudgets[selectedTrip]||0,memberName(e.payerMemberId),(e.splitMemberIds||[]).map(memberName).join(" | "),"平均分帳",(e.splitShares||[]).map(share=>`${memberName(share.memberId)}=${e.currency} ${share.amount}`).join(" | ")].map(csvCell).join(","));download(`\uFEFF${header.map(csvCell).join(",")}\n${rows.join("\n")}`,`my-expenses-${selectedTrip}-${today()}.csv`,"text/csv;charset=utf-8");notify("行程 CSV 已匯出")}
  async function importData(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;try{const parsed=JSON.parse(await file.text()),raw=parsed?.data||parsed;if(!Array.isArray(raw.expenses)||!Array.isArray(raw.categories)||!raw.rates)throw new Error();const restored=normalizeData(raw);if(raw.kind==="trip"||raw.tripName){const name=String(raw.tripName||restored.expenses[0]?.tripName||"").trim();if(!name)throw new Error();setExpenses(current=>{const ids=new Set(restored.expenses.map(e=>e.id));return[...current.filter(e=>!ids.has(e.id)),...restored.expenses]});setCategories(current=>[...current,...restored.categories.filter(c=>!current.some(old=>old.id===c.id))]);setRates(current=>({...current,...restored.rates}));setTripBudgets(current=>({...current,[name]:restored.tripBudgets[name]||0}));setTripRates(current=>({...current,[name]:restored.tripRates[name]||{}}));setTripLastCurrencies(current=>({...current,...(restored.tripLastCurrencies[name]?{[name]:restored.tripLastCurrencies[name]}:{})}));setTripSplits(current=>({...current,[name]:restored.tripSplits[name]||defaultTripSplit(name)}));setSelectedTrip(name);setMode("travel");notify("單一行程已匯入")}else{await writeDatabase(restored);mirror(restored);setExpenses(restored.expenses);setCategories(restored.categories);setRates(restored.rates);setMonthlyBudgets(restored.monthlyBudgets);setTripBudgets(restored.tripBudgets);setTripRates(restored.tripRates);setTripLastCurrencies(restored.tripLastCurrencies);setTripSplits(restored.tripSplits);setRateUpdated(restored.settings.rateUpdated);setMode(restored.settings.lastMode||"daily");setChartMode(restored.settings.chartMode||"bar");const restoredTrips=[...new Set(restored.expenses.filter(e=>e.expenseType==="travel"&&e.tripName).map(e=>e.tripName!))];setSelectedTrip(restoredTrips.includes(restored.settings.lastTrip||"")?restored.settings.lastTrip!:(restoredTrips[0]||""));setMonth(today().slice(0,7));notify("所有資料已完整還原")}}catch{notify("備份檔案格式不正確")}}
  if(!ready)return <main className="loading">My Expenses</main>;
  return <main className="app-shell"><div className="app-frame"><header className="topbar"><div><p className="eyebrow">MY EXPENSES</p><h1>{tab==="dashboard"?"你好":tab==="records"?"支出記錄":tab==="categories"?"支出分類":"設定"}</h1></div><div className="avatar">$</div></header>
    {(tab==="dashboard"||tab==="records")&&<ModeBar mode={mode} setMode={setMode} tripNames={tripNames} selectedTrip={selectedTrip} setSelectedTrip={setSelectedTrip}/>}
    {tab==="dashboard"&&<Dashboard mode={mode} dailyScope={dailyScope} setDailyScope={setDailyScope} month={month} selectedTrip={selectedTrip} total={total} monthlyBudget={monthlyBudgets[month]||0} budget={tripBudgets[selectedTrip]||0} expenses={visible} allExpenses={expenses} categories={categories} breakdown={breakdown} chartMode={chartMode} setChartMode={setChartMode} tripTotals={tripTotals} splitConfig={selectedTrip?tripSplits[selectedTrip]||defaultTripSplit(selectedTrip):undefined} shiftMonth={shiftMonth} setMonthlyBudget={value=>setMonthlyBudgets(current=>({...current,[month]:value}))} setBudget={value=>selectedTrip&&setTripBudgets(v=>({...v,[selectedTrip]:value}))} edit={e=>{setEditing(e);setEditorOpen(true)}} enableSplit={()=>{if(!selectedTrip)return;setTripSplits(v=>({...v,[selectedTrip]:{...(v[selectedTrip]||defaultTripSplit(selectedTrip)),enabled:true}}));setMemberManagerOpen(true)}} hideSplit={()=>selectedTrip&&setTripSplits(v=>({...v,[selectedTrip]:{...(v[selectedTrip]||defaultTripSplit(selectedTrip)),enabled:false}}))} manageMembers={()=>setMemberManagerOpen(true)} exportJson={exportTripJson} exportCsv={exportTripCsv}/>}
    {tab==="records"&&<Records expenses={mode==="daily"?expenses.filter(e=>e.expenseType!=="travel"):visible} categories={categories} edit={e=>{setEditing(e);setEditorOpen(true)}}/>}
    {tab==="categories"&&<Categories categories={categories} expenses={expenses} open={setCategoryModal}/>}
    {tab==="settings"&&<Settings rates={rates} updated={rateUpdated} setRates={setRates} refresh={refreshRates} exportData={exportData} importData={()=>importRef.current?.click()}/>}
    <nav className="bottom-nav" aria-label="主要導覽"><NavButton active={tab==="dashboard"} icon="▦" label="總覽" onClick={()=>setTab("dashboard")}/><NavButton active={tab==="records"} icon="≡" label="記錄" onClick={()=>setTab("records")}/><button className="add-button" onClick={()=>{setEditing(null);setEditorOpen(true)}} aria-label="新增支出">＋</button><NavButton active={tab==="categories"} icon="◫" label="分類" onClick={()=>setTab("categories")}/><NavButton active={tab==="settings"} icon="⚙" label="設定" onClick={()=>setTab("settings")}/></nav></div>
    {editorOpen&&<ExpenseEditor categories={categories} rates={rates} tripRates={tripRates} tripLastCurrencies={tripLastCurrencies} tripSplits={tripSplits} expense={editing} defaultType={mode} defaultTrip={selectedTrip} recent={expenses} notify={notify} addCategory={(name,subs)=>{if(categories.some(c=>c.name===name)){notify("已有相同名稱的分類");return null}const category={id:makeId(),name,subcategories:subs};setCategories(v=>[...v,category]);notify("分類已儲存");return category}} onClose={()=>setEditorOpen(false)} onSave={saveExpense} onDelete={editing?()=>deleteExpense(editing.id):undefined}/>}
    {memberManagerOpen&&selectedTrip&&<MemberManager config={tripSplits[selectedTrip]||defaultTripSplit(selectedTrip)} expenses={expenses.filter(e=>e.expenseType==="travel"&&e.tripName===selectedTrip)} notify={notify} onClose={()=>setMemberManagerOpen(false)} onChange={config=>setTripSplits(v=>({...v,[selectedTrip]:config}))}/>}
    {categoryModal&&<CategoryEditor value={categoryModal==="new"?null:categoryModal} onClose={()=>setCategoryModal(null)} onSave={(name,subs)=>{if(categories.some(c=>c.name===name&&(categoryModal==="new"||c.id!==categoryModal.id))){notify("已有相同名稱的分類");return}if(categoryModal==="new")setCategories(v=>[...v,{id:makeId(),name,subcategories:subs}]);else setCategories(v=>v.map(c=>c.id===categoryModal.id?{...c,name,subcategories:subs}:c));setCategoryModal(null);notify("分類已儲存")}} onDelete={categoryModal==="new"?undefined:()=>{if(expenses.some(e=>e.categoryId===categoryModal.id))return notify("此分類仍有支出，不能刪除");setCategories(v=>v.filter(c=>c.id!==categoryModal.id));setCategoryModal(null);notify("分類已刪除")}}/>}
    <input ref={importRef} className="visually-hidden" type="file" accept="application/json,.json" onChange={importData}/>{toast&&<div className="toast">{toast}</div>}</main>
}

function ModeBar({mode,setMode,tripNames,selectedTrip,setSelectedTrip}:{mode:ExpenseType;setMode:(v:ExpenseType)=>void;tripNames:string[];selectedTrip:string;setSelectedTrip:(v:string)=>void}){return <section className="content mode-area"><div className="mode-switch"><button className={mode==="daily"?"selected":""} onClick={()=>setMode("daily")}>日常</button><button className={mode==="travel"?"selected":""} onClick={()=>{if(!selectedTrip&&tripNames[0])setSelectedTrip(tripNames[0]);setMode("travel")}}>旅行</button></div>{mode==="travel"&&<select className="trip-select" value={selectedTrip} onChange={e=>setSelectedTrip(e.target.value)}><option value="">新增支出以建立行程</option>{tripNames.map(name=><option key={name}>{name}</option>)}</select>}</section>}
type BreakdownItem=Category&{total:number};
function Dashboard({mode,dailyScope,setDailyScope,month,selectedTrip,total,monthlyBudget,budget,expenses,allExpenses,categories,breakdown,chartMode,setChartMode,tripTotals,splitConfig,shiftMonth,setMonthlyBudget,setBudget,edit,enableSplit,hideSplit,manageMembers,exportJson,exportCsv}:{mode:ExpenseType;dailyScope:"daily"|"all";setDailyScope:(v:"daily"|"all")=>void;month:string;selectedTrip:string;total:number;monthlyBudget:number;budget:number;expenses:Expense[];allExpenses:Expense[];categories:Category[];breakdown:BreakdownItem[];chartMode:ChartMode;setChartMode:(mode:ChartMode)=>void;tripTotals:{name:string;total:number}[];splitConfig?:TripSplit;shiftMonth:(v:number)=>void;setMonthlyBudget:(v:number)=>void;setBudget:(v:number)=>void;edit:(e:Expense)=>void;enableSplit:()=>void;hideSplit:()=>void;manageMembers:()=>void;exportJson:()=>void;exportCsv:()=>void}){
  const remaining=budget-total,percent=budget?total/budget*100:0;
  const previousMonth=previousMonthKey(month);
  const previousExpenses=useMemo(()=>allExpenses.filter(expense=>monthKey(expense.date)===previousMonth&&(dailyScope==="all"||expense.expenseType!=="travel")),[allExpenses,previousMonth,dailyScope]);
  const monthlySummary=useMemo(()=>buildMonthlySummary(month,expenses,previousExpenses,categories),[month,expenses,previousExpenses,categories]);
  return <section className="content">
  {mode==="daily"?<><div className="month-switch"><button onClick={()=>shiftMonth(-1)}>‹</button><strong>{monthTitle(month)}</strong><button onClick={()=>shiftMonth(1)}>›</button></div><div className="scope-switch"><button className={dailyScope==="daily"?"selected":""} onClick={()=>setDailyScope("daily")}>只計日常</button><button className={dailyScope==="all"?"selected":""} onClick={()=>setDailyScope("all")}>包括旅行</button></div></>:<div className="trip-heading"><strong>{selectedTrip||"尚未建立行程"}</strong><span>{expenses.length} 筆支出</span></div>}
  <article className="total-card"><span>{mode==="daily"?"本月總支出":"行程總支出"}</span><strong>{money(total)}</strong><small>{expenses.length} 筆支出 · 全部已換算港幣</small><div className="soft-orb"/></article>
  {mode==="daily"&&<details className="card monthly-budget"><summary><span>月度預算</span><strong>{monthlyBudget?money(monthlyBudget):"未設定"}</strong></summary><div><label>HK$ <input type="number" min="0" step="any" value={monthlyBudget||""} placeholder="0" onChange={event=>setMonthlyBudget(Math.max(0,Number(event.target.value)||0))}/></label><small>只屬於 {monthTitle(month)}，月結會按目前「{dailyScope==="daily"?"只計日常":"包括旅行"}」範圍顯示使用進度。</small></div></details>}
  {mode==="travel"&&selectedTrip&&<article className={`card budget-card ${budget&&remaining<0?"over":""}`}><div className="budget-head"><div><h2>旅程預算</h2><p>{budget?(remaining>=0?`尚餘 ${money(remaining)}`:`已超支 ${money(-remaining)}`):"設定 HKD 預算以追蹤進度"}</p></div><label>HK$ <input type="number" min="0" step="any" value={budget||""} placeholder="0" onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label></div><div className="budget-progress"><i style={{width:`${Math.min(percent,100)}%`}}/></div><small>{budget?`已使用 ${percent.toFixed(1)}%${remaining<0?" · 超支":""}`:"尚未設定預算"}</small></article>}
  {mode==="travel"&&selectedTrip&&(!splitConfig?.enabled?<button className="split-enable" onClick={enableSplit}>啟用分帳</button>:<article className="card split-toolbar"><div><strong>同行分帳已啟用</strong><small>{splitConfig.members.filter(member=>member.active).length} 位啟用成員</small></div><div><button onClick={manageMembers}>同行成員</button><button onClick={hideSplit}>隱藏分帳功能</button></div></article>)}
  {mode==="travel"&&selectedTrip&&splitConfig?.enabled&&<SettlementPanel expenses={expenses} config={splitConfig}/>}
  {mode==="travel"&&tripTotals.length>1&&<><div className="section-title"><h2>行程比較</h2><span>{tripTotals.length} 個行程</span></div><article className="card trip-compare">{tripTotals.map(t=><div key={t.name} className={t.name===selectedTrip?"current":""}><span>{t.name}</span><strong>{money(t.total)}</strong></div>)}</article></>}
  <div className="section-title chart-title"><h2>分類支出</h2><div className="chart-switch" aria-label="分類圖表顯示方式"><button className={chartMode==="bar"?"selected":""} onClick={()=>setChartMode("bar")}>橫條</button><button className={chartMode==="donut"?"selected":""} onClick={()=>setChartMode("donut")}>圓環</button></div></div>{chartMode==="donut"?<DonutChart breakdown={breakdown} total={total} totalLabel={mode==="daily"?"本月總支出":"行程總支出"} expenses={expenses} edit={edit}/>:<article className="card category-summary">{breakdown.length?breakdown.map((c,i)=><div className="category-row" key={c.id}><div className={`category-icon tone-${i%4}`}>{c.name.slice(0,1)}</div><div className="category-data"><div><strong>{c.name}</strong><span>{money(c.total)}</span></div><div className="bar"><i style={{width:`${total?c.total/total*100:0}%`}}/></div><small>{total?(c.total/total*100).toFixed(1):0}%</small></div></div>):<Empty text={mode==="daily"?"今個月未有支出":"此行程未有支出"}/>}</article>}
  {mode==="daily"&&monthClosed(month)&&<MonthlySummaryCard summary={monthlySummary} categories={categories} scope={dailyScope} budget={monthlyBudget}/>}
  <div className="section-title"><h2>最近支出</h2></div><article className="card record-list">{expenses.slice(0,5).map(e=><ExpenseRow key={e.id} e={e} category={categories.find(c=>c.id===e.categoryId)} onClick={()=>edit(e)}/>)}{!expenses.length&&<Empty text="撳下面 ＋ 新增第一筆支出"/>}</article>
  {mode==="travel"&&selectedTrip&&<details className="card trip-export-panel"><summary>備份與匯出</summary><div className="trip-export"><button onClick={exportJson}>備份 JSON</button><button onClick={exportCsv}>匯出 CSV</button></div></details>}</section>}
const CHART_COLORS=["#2f8f66","#efad44","#6f78d8","#d96b65","#54a9bd","#9a6fc0","#7da64b","#d184b1"];
function DonutChart({breakdown,total,totalLabel,expenses,edit}:{breakdown:BreakdownItem[];total:number;totalLabel:string;expenses:Expense[];edit:(expense:Expense)=>void}){
  const[selectedId,setSelectedId]=useState("");
  const selected=breakdown.find(item=>item.id===selectedId),selectedExpenses=selectedId?expenses.filter(expense=>expense.categoryId===selectedId):[],radius=48,circumference=2*Math.PI*radius;
  const segments=breakdown.map((item,index)=>{const portion=total?item.total/total:0,prior=breakdown.slice(0,index).reduce((sum,entry)=>sum+(total?entry.total/total:0),0);return{item,index,portion,offset:-prior*circumference}});
  return <article className="card donut-card">{breakdown.length?<><div className="donut-wrap"><svg className="donut-chart" viewBox="0 0 120 120" role="img" aria-label="分類支出圓環圖"><circle className="donut-track" cx="60" cy="60" r={radius}/>{segments.map(({item,index,portion,offset})=><circle key={item.id} className={`donut-segment ${selectedId===item.id?"selected":""}`} cx="60" cy="60" r={radius} stroke={CHART_COLORS[index%CHART_COLORS.length]} strokeDasharray={`${portion*circumference} ${circumference}`} strokeDashoffset={offset} tabIndex={0} role="button" aria-label={`${item.name} ${money(item.total)} ${(portion*100).toFixed(1)}%`} aria-expanded={selectedId===item.id} onClick={()=>setSelectedId(current=>current===item.id?"":item.id)} onKeyDown={event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();setSelectedId(current=>current===item.id?"":item.id)}}}/>)}</svg><div className="donut-center"><small>{selected?.name||totalLabel}</small><strong>{money(selected?.total||total)}</strong>{selected&&<span>{total?(selected.total/total*100).toFixed(1):0}%</span>}</div></div><div className="donut-legend">{breakdown.map((item,index)=><button key={item.id} className={selectedId===item.id?"selected":""} aria-expanded={selectedId===item.id} onClick={()=>setSelectedId(current=>current===item.id?"":item.id)}><i style={{background:CHART_COLORS[index%CHART_COLORS.length]}}/><span>{item.name}</span><strong>{money(item.total)}</strong><small>{total?(item.total/total*100).toFixed(1):0}%</small></button>)}</div>{selected&&<section className="donut-details" aria-label={`${selected.name}支出明細`}><div className="donut-details-head"><div><strong>{selected.name}明細</strong><small>{selectedExpenses.length} 筆支出</small></div><span>{money(selected.total)}</span></div><div className="donut-detail-list">{selectedExpenses.map(expense=><ExpenseRow key={expense.id} e={expense} category={selected} onClick={()=>edit(expense)}/>)}</div></section>}</>:<Empty text="暫時未有分類支出"/>}</article>
}
function MonthlySummaryCard({summary,categories,scope,budget}:{summary:ReturnType<typeof buildMonthlySummary>;categories:Category[];scope:"daily"|"all";budget:number}){
  const largestCategory=summary.largestExpense?categories.find(category=>category.id===summary.largestExpense!.categoryId)?.name||"其他":"—";
  const comparison=summary.changeAmount==null||summary.changePercent==null?null:{direction:summary.changeAmount>=0?"增加":"減少",amount:Math.abs(summary.changeAmount),percent:Math.abs(summary.changePercent)};
  const budgetPercent=budget?summary.total/budget*100:0,remaining=budget-summary.total;
  const budgetTip=budget&&budgetPercent>=90?(remaining>=0?`本月已使用預算 ${budgetPercent.toFixed(1)}%，尚餘 ${money(remaining)}。`:`本月支出比預算多 ${money(-remaining)}，可作下月規劃參考。`):"";
  const tips=(budgetTip?[budgetTip,...summary.tips]:summary.tips).slice(0,2);
  return <details className="card monthly-summary"><summary><div><span>本月月結</span><small>{scope==="daily"?"只計日常":"包括旅行"}</small></div><strong>{money(summary.total)}</strong></summary><div className="monthly-summary-body"><div className="monthly-scope">計算範圍：{scope==="daily"?"只計日常支出":"日常及旅行支出"}</div><div className="monthly-grid"><div><small>本月總支出</small><strong>{money(summary.total)}</strong></div><div><small>與上月相比</small>{comparison?<strong>{comparison.direction} {money(comparison.amount)}（{comparison.percent.toFixed(1)}%）</strong>:<strong>暫時未有足夠資料比較</strong>}</div><div><small>最高支出分類</small><strong>{summary.topCategory?`${summary.topCategory.name} · ${money(summary.topCategory.amount)} · ${summary.topCategory.percent.toFixed(1)}%`:"本月未有支出"}</strong></div><div><small>最大一筆支出</small><strong>{summary.largestExpense?`${largestCategory} · ${money(summary.largestExpense.hkdAmount)}`:"本月未有支出"}</strong></div><div><small>平均每日支出</small><strong>{money(summary.averageDaily)}</strong></div><div><small>無支出日數</small><strong>{summary.noSpendDays} 日</strong></div>{budget>0&&<div><small>月度預算</small><strong>{remaining>=0?`尚餘 ${money(remaining)}`:`超支 ${money(-remaining)}`} · 已使用 {budgetPercent.toFixed(1)}%</strong></div>}</div>{tips.length>0&&<div className="monthly-tips"><h3>簡短提示</h3>{tips.map(tip=><p key={tip}>{tip}</p>)}</div>}</div></details>
}
function SettlementPanel({expenses,config}:{expenses:Expense[];config:TripSplit}){
  const currencies=[...new Set(expenses.map(expense=>expense.currency))];
  const name=(id:string)=>config.members.find(member=>member.memberId===id)?.name||"已封存成員";
  const calculate=(currency:Currency|"HKD_REF")=>config.members.map(member=>{let paid=0,share=0;expenses.forEach(expense=>{const multiplier=currency==="HKD_REF"?expense.rate:1;if(currency!=="HKD_REF"&&expense.currency!==currency)return;if(expense.payerMemberId===member.memberId)paid+=expense.amount*multiplier;(expense.splitShares||[]).filter(item=>item.memberId===member.memberId).forEach(item=>{share+=item.amount*multiplier})});return{memberId:member.memberId,paid,share,amount:paid-share}});
  return <details className="card settlement-panel"><summary>分帳結算</summary><div className="settlement-body">{currencies.map(currency=>{const balances=calculate(currency),transfers=settleBalances(balances,currencyDigits(currency));return <div className="settlement-currency" key={currency}><h3>{currency} 原幣結算</h3>{balances.map(row=><div className="settlement-row" key={row.memberId}><strong>{name(row.memberId)}</strong><span>已付 {originalMoney(row.paid,currency)}</span><span>應付 {originalMoney(row.share,currency)}</span><b className={row.amount>=0?"positive":"negative"}>{row.amount>=0?"應收":"應付"} {originalMoney(Math.abs(row.amount),currency)}</b></div>)}<div className="transfer-list"><strong>建議轉帳</strong>{transfers.length?transfers.map((transfer,index)=><p key={`${transfer.fromMemberId}-${transfer.toMemberId}-${index}`}>{name(transfer.fromMemberId)} → {name(transfer.toMemberId)} <b>{originalMoney(transfer.amount,currency)}</b></p>):<p>已經平數，毋須轉帳</p>}</div></div>})}{expenses.length>0&&<div className="settlement-currency reference"><h3>HKD 綜合換算參考</h3>{calculate("HKD_REF").map(row=><div className="settlement-row" key={row.memberId}><strong>{name(row.memberId)}</strong><span>已付 {money(row.paid)}</span><span>應付 {money(row.share)}</span><b className={row.amount>=0?"positive":"negative"}>{row.amount>=0?"應收":"應付"} {money(Math.abs(row.amount))}</b></div>)}<div className="transfer-list"><strong>參考轉帳</strong>{settleBalances(calculate("HKD_REF"),2).map((transfer,index)=><p key={`${transfer.fromMemberId}-${transfer.toMemberId}-${index}`}>{name(transfer.fromMemberId)} → {name(transfer.toMemberId)} <b>{money(transfer.amount)}</b></p>)}</div><small>按每筆支出已保存匯率換算，不會重新抓取或改動舊匯率。</small></div>}</div></details>
}
function Records({expenses,categories,edit}:{expenses:Expense[];categories:Category[];edit:(e:Expense)=>void}){const groups=expenses.slice().sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).reduce<Record<string,Expense[]>>((o,e)=>{(o[e.date]||=[]).push(e);return o},{});return <section className="content records-page">{Object.entries(groups).map(([date,list])=><div key={date}><div className="day-heading"><strong>{date===today()?"今日":shortDate(date)}</strong><span>{money(list.reduce((s,e)=>s+e.hkdAmount,0))}</span></div><article className="card record-list">{list.map(e=><ExpenseRow key={e.id} e={e} category={categories.find(c=>c.id===e.categoryId)} onClick={()=>edit(e)}/>)}</article></div>)}{!expenses.length&&<article className="card"><Empty text="暫時未有支出記錄"/></article>}</section>}
function Categories({categories,expenses,open}:{categories:Category[];expenses:Expense[];open:(c:Category|"new")=>void}){return <section className="content"><p className="page-lead">管理分類及其細分類。</p><article className="card manage-list">{categories.map(c=><button key={c.id} onClick={()=>open(c)}><span className="category-icon">{c.name.slice(0,1)}</span><span><strong>{c.name}</strong><small>{c.subcategories?.length?`${c.subcategories.join(" · ")} · `:""}{expenses.filter(e=>e.categoryId===c.id).length} 筆記錄</small></span><b>›</b></button>)}</article><button className="secondary-action" onClick={()=>open("new")}>＋ 新增分類</button></section>}
function Settings({rates,updated,setRates,refresh,exportData,importData}:{rates:Record<Currency,number>;updated:string;setRates:React.Dispatch<React.SetStateAction<Record<Currency,number>>>;refresh:()=>void;exportData:()=>void;importData:()=>void}){return <section className="content"><article className="card settings-card"><div className="setting-title"><div><h2>參考匯率</h2><p>1 單位外幣可兌換的港幣</p></div><button onClick={refresh}>自動更新</button></div>{CURRENCIES.filter(c=>c.code!=="HKD").map(c=><label className="rate-line" key={c.code}><span><strong>{c.code}</strong><small>{c.label}</small></span><div><input type="number" step=".000001" value={rates[c.code]} onChange={e=>setRates(v=>({...v,[c.code]:Number(e.target.value)}))}/><em>HKD</em></div></label>)}<small className="updated">{updated} · 網絡失敗時使用</small></article><article className="card about-card"><h2>資料備份</h2><p>包含全部支出、分類、貨幣、參考匯率、旅程預算、行程鎖定匯率及設定。完整備份或單一行程 JSON 都可匯入。</p><div className="backup-actions"><button onClick={exportData}>匯出完整備份</button><button onClick={importData}>匯入 JSON</button></div></article><article className="card about-card"><h2>資料保存</h2><p>資料使用這部裝置瀏覽器的 IndexedDB 保存，並建立 localStorage 後備副本。清除 Safari 網站資料會同時刪除記錄。</p></article><article className="card about-card"><h2>Base Currency</h2><p>HKD 港幣 · 所有統計均以港幣顯示</p></article></section>}

function ExpenseEditor({categories,rates,tripRates,tripLastCurrencies,tripSplits,expense,defaultType,defaultTrip,recent,notify,addCategory,onClose,onSave,onDelete}:{categories:Category[];rates:Record<Currency,number>;tripRates:TripRates;tripLastCurrencies:TripLastCurrencies;tripSplits:TripSplits;expense:Expense|null;defaultType:ExpenseType;defaultTrip:string;recent:Expense[];notify:(v:string)=>void;addCategory:(name:string,subs:string[])=>Category|null;onClose:()=>void;onSave:(e:Omit<Expense,"id"|"createdAt">)=>void;onDelete?:()=>void}){
  const initialCurrency=expense?.currency||(!expense&&defaultType==="travel"&&defaultTrip?tripLastCurrencies[defaultTrip]:undefined)||"HKD",initialRate=expense?.rate||tripRates[defaultTrip]?.[initialCurrency]||rates[initialCurrency];
  const initialSplit=defaultTrip?tripSplits[defaultTrip]:undefined;
  const[amount,setAmount]=useState(expense?.amount.toString()||""),[currency,setCurrency]=useState<Currency>(initialCurrency),[rate,setRate]=useState(initialRate),[expenseType,setExpenseType]=useState<ExpenseType>(expense?.expenseType||defaultType),[tripName,setTripName]=useState(expense?.tripName||defaultTrip),[loading,setLoading]=useState(false),[categoryId,setCategoryId]=useState(expense?.categoryId||""),[subcategory,setSubcategory]=useState(expense?.subcategory||""),[date,setDate]=useState(expense?.date||today()),[note,setNote]=useState(expense?.note||""),[addingCategory,setAddingCategory]=useState(false),[calculatorOpen,setCalculatorOpen]=useState(false),[payerId,setPayerId]=useState(expense?.payerMemberId||initialSplit?.lastPayerId||""),[splitIds,setSplitIds]=useState<string[]>(expense?.splitMemberIds||initialSplit?.members.filter(member=>member.active).map(member=>member.memberId)||[]);
  const trip=tripName.trim(),splitConfig=expenseType==="travel"&&trip?tripSplits[trip]:undefined,splitEnabled=splitConfig?.enabled===true,locked=expenseType==="travel"&&trip?tripRates[trip]?.[currency]:undefined,popular=[...new Set(recent.map(e=>e.categoryId))].map(id=>categories.find(c=>c.id===id)).filter(Boolean).slice(0,4) as Category[],ordered=[...popular,...categories.filter(c=>!popular.some(p=>p.id===c.id))],selected=categories.find(c=>c.id===categoryId),hkd=(Number(amount)||0)*(locked??rate);
  async function chooseCurrency(next:Currency,type=expenseType,name=trip){setCurrency(next);if(expense&&next===expense.currency&&type===expense.expenseType&&name===expense.tripName){setRate(expense.rate);return}const fixed=type==="travel"&&name?tripRates[name]?.[next]:undefined;if(fixed!=null){setRate(fixed);return}setLoading(true);const latest=await fetchRate(next,rates[next]);setRate(latest);setLoading(false);if(latest===rates[next]&&next!=="HKD")notify("未能取得最新匯率，已使用保存的參考匯率")}
  function applyTripCurrency(name:string){const preferred=tripLastCurrencies[name]||currency;void chooseCurrency(preferred,"travel",name);const config=tripSplits[name];if(config?.enabled){setPayerId(expense?.payerMemberId||config.lastPayerId);setSplitIds(expense?.splitMemberIds||config.members.filter(member=>member.active).map(member=>member.memberId))}}
  function submit(e:FormEvent){e.preventDefault();if(!amount||Number(amount)<=0||!categoryId||loading||(expenseType==="travel"&&!trip)||(splitEnabled&&(!payerId||!splitIds.length)))return;const finalRate=locked??rate,splitShares=splitEnabled?splitAmount(Number(amount),splitIds,currencyDigits(currency)):undefined;onSave({amount:Number(amount),currency,hkdAmount:Number(amount)*finalRate,rate:finalRate,categoryId,subcategory:subcategory||undefined,date,note:note.trim(),expenseType,tripName:expenseType==="travel"?trip:undefined,payerMemberId:splitEnabled?payerId:expense?.payerMemberId,splitMemberIds:splitEnabled?splitIds:expense?.splitMemberIds,splitShares:splitEnabled?splitShares:expense?.splitShares})}
  return <><div className="modal-backdrop"><form className="sheet" onSubmit={submit}><div className="sheet-handle"/><div className="sheet-head"><button type="button" onClick={onClose}>取消</button><h2>{expense?"編輯支出":"新增支出"}</h2><button disabled={!amount||!categoryId||loading||(expenseType==="travel"&&!trip)||(splitEnabled&&(!payerId||!splitIds.length))}>儲存</button></div><div className="editor-mode mode-switch"><button type="button" className={expenseType==="daily"?"selected":""} onClick={()=>{setExpenseType("daily");void chooseCurrency(currency,"daily","")}}>日常</button><button type="button" className={expenseType==="travel"?"selected":""} onClick={()=>{setExpenseType("travel");if(trip)applyTripCurrency(trip)}}>旅行</button></div>
    {expenseType==="travel"&&<label className="form-line"><span>行程名稱</span><input value={tripName} onChange={e=>setTripName(e.target.value)} onBlur={()=>trip&&applyTripCurrency(trip)} placeholder="例如：釜山 2026" required/></label>}
    <div className="amount-entry"><div className="amount-controls"><select value={currency} onChange={e=>void chooseCurrency(e.target.value as Currency)}>{CURRENCIES.map(c=><option key={c.code}>{c.code}</option>)}</select><input autoFocus inputMode="decimal" type="number" min="0" step="any" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value)}/><button type="button" className="calculator-trigger" aria-label="開啟計數機" title="簡易計數機" onClick={()=>setCalculatorOpen(true)}><svg aria-hidden="true" viewBox="0 0 24 24"><rect x="4" y="2.5" width="16" height="19" rx="3"/><path d="M7.5 6.5h9v3h-9z"/><circle cx="8" cy="13" r="1"/><circle cx="12" cy="13" r="1"/><circle cx="16" cy="13" r="1"/><circle cx="8" cy="17" r="1"/><circle cx="12" cy="17" r="1"/><path d="M16 16v2M15 17h2"/></svg></button></div><small>{loading?"正在取得最新匯率…":`≈ ${money(hkd)} HKD`}</small></div>
    {currency!=="HKD"&&<label className="form-line"><span>匯率 {locked!=null&&<small>（行程已鎖定）</small>}</span><div className="inline-rate"><input type="number" step=".000001" value={locked??rate} disabled={locked!=null||loading} onChange={e=>setRate(Number(e.target.value))}/><small>HKD / {currency}</small></div></label>}
    <div className="form-block"><span>分類</span><div className="category-chips">{ordered.map((c,i)=><button type="button" className={categoryId===c.id?"selected":""} key={c.id} onClick={()=>{setCategoryId(c.id);setSubcategory("")}}>{i<popular.length&&<i>常用</i>}{c.name}</button>)}</div>{expenseType==="travel"&&<button className="inline-add-category" type="button" onClick={()=>setAddingCategory(true)}>＋ 新增分類</button>}</div>
    {selected?<div className="form-block subcategory-choice"><span>細分類 <small>選填</small></span>{selected.subcategories?.length?<div className="category-chips"><button type="button" className={!subcategory?"selected":""} onClick={()=>setSubcategory("")}>不指定</button>{selected.subcategories.map(s=><button type="button" className={subcategory===s?"selected":""} key={s} onClick={()=>setSubcategory(s)}>{s}</button>)}</div>:<p className="subcategory-empty">此分類未有已保存的細分類，請到「分類」頁加入後按右上角「儲存」。</p>}</div>:null}
    {splitEnabled&&splitConfig&&<><label className="form-line"><span>付款人</span><select value={payerId} onChange={e=>setPayerId(e.target.value)}>{splitConfig.members.filter(member=>member.active||member.memberId===payerId).map(member=><option key={member.memberId} value={member.memberId}>{member.name}{!member.active?"（已停用）":""}</option>)}</select></label><div className="form-block"><span>分擔成員 <small>平均分帳</small></span><div className="member-chips">{splitConfig.members.filter(member=>member.active||splitIds.includes(member.memberId)).map(member=><button type="button" key={member.memberId} className={splitIds.includes(member.memberId)?"selected":""} onClick={()=>setSplitIds(current=>current.includes(member.memberId)?current.filter(id=>id!==member.memberId):[...current,member.memberId])}>{splitIds.includes(member.memberId)?"✓ ":""}{member.name}{!member.active?"（已停用）":""}</button>)}</div>{!splitIds.length&&<small className="field-error">最少選擇一位分擔成員</small>}{splitIds.length>0&&Number(amount)>0&&<div className="share-preview">{splitAmount(Number(amount),splitIds,currencyDigits(currency)).map(share=><span key={share.memberId}>{splitConfig.members.find(member=>member.memberId===share.memberId)?.name}: {originalMoney(share.amount,currency)}</span>)}</div>}</div></>}
    <label className="form-line"><span>日期</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="form-block"><span>備註 <small>選填</small></span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="例如：韓國旅行晚餐"/></label>{onDelete&&<button className="delete-button" type="button" onClick={onDelete}>刪除這筆支出</button>}</form></div>{addingCategory&&<CategoryEditor value={null} onClose={()=>setAddingCategory(false)} onSave={(name,subs)=>{const category=addCategory(name,subs);if(!category)return;setCategoryId(category.id);setSubcategory("");setAddingCategory(false)}}/>}{calculatorOpen&&<Calculator initial={amount} onClose={()=>setCalculatorOpen(false)} onUse={value=>{setAmount(value);setCalculatorOpen(false)}}/>}</>
}
function Calculator({initial,onClose,onUse}:{initial:string;onClose:()=>void;onUse:(value:string)=>void}){
  const[expression,setExpression]=useState(initial||""),[result,setResult]=useState(initial||"0"),[error,setError]=useState("");
  function evaluate(){try{const value=calculateExpression(expression);setResult(Number.isInteger(value)?String(value):String(Number(value.toFixed(8))));setError("")}catch(reason){setError(reason instanceof Error&&reason.message==="DIV_ZERO"?"不能除以零":reason instanceof Error&&reason.message==="TOO_LARGE"?"數字太大":"算式無效")}}
  function press(key:string){setError("");if(key==="C"){setExpression("");setResult("0");return}if(key==="⌫"){setExpression(value=>value.slice(0,-1));return}if(key==="="){evaluate();return}setExpression(value=>value.length>=120?value:`${value}${key}`)}
  return <div className="modal-backdrop calculator-layer"><div className="mini-sheet calculator"><div className="sheet-head"><button type="button" onClick={onClose}>關閉</button><h2>簡易計數機</h2><span/></div><div className="calculator-display"><small>{expression||"輸入算式"}</small><strong>{error||result}</strong></div><div className="calculator-grid">{["C","⌫","÷","×","7","8","9","-","4","5","6","+","1","2","3","=","0","."].map(key=><button type="button" key={key} className={key==="="?"equals":["÷","×","-","+"].includes(key)?"operator":["C","⌫"].includes(key)?"utility":"number-key"} onClick={()=>press(key)}>{key}</button>)}</div><button className="calculator-use" type="button" disabled={!!error||!expression} onClick={()=>{try{const value=calculateExpression(expression);if(value<0){setError("金額不可為負數");return}onUse(Number.isInteger(value)?String(value):String(Number(value.toFixed(8))))}catch{evaluate()}}}>使用此金額</button></div></div>
}
function MemberManager({config,expenses,notify,onClose,onChange}:{config:TripSplit;expenses:Expense[];notify:(message:string)=>void;onClose:()=>void;onChange:(config:TripSplit)=>void}){
  const[newName,setNewName]=useState("");
  const usedIds=new Set(expenses.flatMap(expense=>[expense.payerMemberId,...(expense.splitMemberIds||[])]).filter(Boolean));
  function add(){const name=newName.trim();if(!name)return;if(config.members.some(member=>member.name===name)){notify("同一旅程已有相同名稱");return}onChange({...config,members:[...config.members,{memberId:makeId(),name,active:true}]});setNewName("")}
  function rename(memberId:string,name:string){const trimmed=name.trim();if(!trimmed||config.members.some(member=>member.memberId!==memberId&&member.name===trimmed)){notify(!trimmed?"成員名稱不可留空":"同一旅程已有相同名稱");return}onChange({...config,members:config.members.map(member=>member.memberId===memberId?{...member,name:trimmed}:member)})}
  function toggle(memberId:string){const member=config.members.find(item=>item.memberId===memberId);if(!member)return;if(member.memberId===config.members[0].memberId&&member.active){notify("我自己需要保留啟用");return}onChange({...config,members:config.members.map(item=>item.memberId===memberId?{...item,active:!item.active}:item)})}
  return <div className="modal-backdrop"><div className="mini-sheet member-manager"><div className="sheet-head"><button type="button" onClick={onClose}>完成</button><h2>同行成員</h2><span/></div><p>每個旅程獨立保存；停用成員仍會保留舊記錄。</p><div className="member-list">{config.members.map(member=><div key={member.memberId}><input aria-label={`${member.name}名稱`} defaultValue={member.name} onBlur={event=>rename(member.memberId,event.target.value)}/><button type="button" className={member.active?"active":""} onClick={()=>toggle(member.memberId)}>{member.active?"啟用中":usedIds.has(member.memberId)?"已停用 · 保留舊帳":"已停用"}</button></div>)}</div><div className="member-add"><input value={newName} onChange={event=>setNewName(event.target.value)} placeholder="同行成員姓名"/><button type="button" onClick={add}>＋ 新增同行成員</button></div></div></div>
}
function CategoryEditor({value,onClose,onSave,onDelete}:{value:Category|null;onClose:()=>void;onSave:(n:string,s:string[])=>void;onDelete?:()=>void}){const[name,setName]=useState(value?.name||""),[subs,setSubs]=useState<string[]>(value?.subcategories||[]),[newSub,setNewSub]=useState("");function pendingSubs(){return cleanSubcategories([...subs,...newSub.split(/[，,、\n]/)])}function add(){const next=pendingSubs();if(next.length!==subs.length)setSubs(next);setNewSub("")}return <div className="modal-backdrop"><form className="mini-sheet" onSubmit={e=>{e.preventDefault();if(name.trim())onSave(name.trim(),pendingSubs())}}><div className="sheet-head"><button type="button" onClick={onClose}>取消</button><h2>{value?"編輯分類":"新增分類"}</h2><button disabled={!name.trim()}>儲存</button></div><label>分類名稱<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="輸入分類名稱"/></label><div className="subcategory-editor"><strong>細分類</strong><div className="subcategory-add"><input value={newSub} onChange={e=>setNewSub(e.target.value)} placeholder="例如：巴士"/><button type="button" onClick={add}>加入</button></div><small>加入後仍要按右上角「儲存」；直接按「儲存」亦會保留輸入框中的細分類。</small><div className="subcategory-list">{subs.map((s,i)=><span key={`${s}-${i}`}>{s}<button type="button" onClick={()=>setSubs(v=>v.filter((_,x)=>x!==i))}>×</button></span>)}</div></div>{onDelete&&<button type="button" className="delete-button" onClick={onDelete}>刪除分類</button>}</form></div>}
function ExpenseRow({e,category,onClick}:{e:Expense;category?:Category;onClick:()=>void}){return <button className="expense-row" onClick={onClick}><span className="category-icon">{category?.name.slice(0,1)||"其"}</span><span className="expense-main"><strong>{category?.name||"其他"}{e.subcategory?` · ${e.subcategory}`:""}</strong><small>{shortDate(e.date)}{e.tripName?` · ${e.tripName}`:""}{e.note?` · ${e.note}`:""}</small></span><span className="expense-money"><strong>{money(e.hkdAmount)}</strong>{e.currency!=="HKD"&&<small>{originalMoney(e.amount,e.currency)}</small>}</span></button>}
function NavButton({active,icon,label,onClick}:{active:boolean;icon:string;label:string;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}><i>{icon}</i><span>{label}</span></button>}
function Empty({text}:{text:string}){return <div className="empty"><div>✓</div><p>{text}</p></div>}
